/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HighlanderPlayer} from './HighlanderPlayer';
import {HighlanderPlayerChampions} from './HighlanderPlayerChampions';

/**
 * The AllOfinlineResponse20014PlayersItems model module.
 * @module model/AllOfinlineResponse20014PlayersItems
 * @version 1.0.0-alpha-1
 */
export class AllOfinlineResponse20014PlayersItems extends HighlanderPlayer {
  /**
   * Constructs a new <code>AllOfinlineResponse20014PlayersItems</code>.
   * @alias module:model/AllOfinlineResponse20014PlayersItems
   * @class
   * @extends module:model/HighlanderPlayer
   * @param id {} The player ID
   * @param slug {} URL friendly version of the player's in game name
   * @param name {} The player's in game name
   * @param firstName {} 
   * @param roleSlug {} The role they usually play
   * @param photoUrl {} URL to the player's photo
   * @param hometown {} 
   * @param region {} 
   * @param birthdate {} 
   * @param createdAt {} The date and time when this entry was created.
   * @param updatedAt {} The date and time when this entry was last updated.
   * @param bios {} Contains a description of the player translated to various languages.  The keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))  `{languageCode}_{countryCode}`  The value is a string containing html tags representing the description in that specific locale. 
   * @param foreignIds {} 
   * @param socialNetworks {} Contains links to the player's social media accounts.  The key is the name of the social media platform and the value is the URL 
   * @param champions {} 
   */
  constructor(id, slug, name, firstName, roleSlug, photoUrl, hometown, region, birthdate, createdAt, updatedAt, bios, foreignIds, socialNetworks, champions) {
    super(id, slug, name, firstName, roleSlug, photoUrl, hometown, region, birthdate, createdAt, updatedAt, bios, foreignIds, socialNetworks, champions);
  }

  /**
   * Constructs a <code>AllOfinlineResponse20014PlayersItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfinlineResponse20014PlayersItems} obj Optional instance to populate.
   * @return {module:model/AllOfinlineResponse20014PlayersItems} The populated <code>AllOfinlineResponse20014PlayersItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfinlineResponse20014PlayersItems();
      HighlanderPlayer.constructFromObject(data, obj);
      if (data.hasOwnProperty('teamRosterStat'))
        obj.teamRosterStat = ApiClient.convertToType(data['teamRosterStat'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} teamRosterStat
 */
AllOfinlineResponse20014PlayersItems.prototype.teamRosterStat = undefined;

