/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ExtendedLeague} from './ExtendedLeague';

/**
 * The AllOfinlineResponse200DataLeaguesItems model module.
 * @module model/AllOfinlineResponse200DataLeaguesItems
 * @version 1.0.0-alpha-1
 */
export class AllOfinlineResponse200DataLeaguesItems extends ExtendedLeague {
  /**
   * Constructs a new <code>AllOfinlineResponse200DataLeaguesItems</code>.
   * @alias module:model/AllOfinlineResponse200DataLeaguesItems
   * @class
   * @extends module:model/ExtendedLeague
   * @param priority {} Unknown
   * @param region {} Indicates which type of tournament the league is. Whether international or a regional tournament. The region name is given. 
   */
  constructor(priority, region) {
    super(id, image, priority);
    this.region = region;
  }

  /**
   * Constructs a <code>AllOfinlineResponse200DataLeaguesItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfinlineResponse200DataLeaguesItems} obj Optional instance to populate.
   * @return {module:model/AllOfinlineResponse200DataLeaguesItems} The populated <code>AllOfinlineResponse200DataLeaguesItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfinlineResponse200DataLeaguesItems();
      ExtendedLeague.constructFromObject(data, obj);
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
    }
    return obj;
  }
}

/**
 * Indicates which type of tournament the league is. Whether international or a regional tournament. The region name is given. 
 * @member {String} region
 */
AllOfinlineResponse200DataLeaguesItems.prototype.region = undefined;

