/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SimpleRoster} from './SimpleRoster';

/**
 * The AllOfhighlanderMatchInputItems model module.
 * @module model/AllOfhighlanderMatchInputItems
 * @version 1.0.0-alpha-1
 */
export class AllOfhighlanderMatchInputItems extends SimpleRoster {
  /**
   * Constructs a new <code>AllOfhighlanderMatchInputItems</code>.
   * @alias module:model/AllOfhighlanderMatchInputItems
   * @class
   * @extends module:model/SimpleRoster
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AllOfhighlanderMatchInputItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfhighlanderMatchInputItems} obj Optional instance to populate.
   * @return {module:model/AllOfhighlanderMatchInputItems} The populated <code>AllOfhighlanderMatchInputItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfhighlanderMatchInputItems();
      SimpleRoster.constructFromObject(data, obj);
      if (data.hasOwnProperty('standing'))
        obj.standing = ApiClient.convertToType(data['standing'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} standing
 */
AllOfhighlanderMatchInputItems.prototype.standing = undefined;

