/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Game} from './Game';
import {SimpleEvent} from './SimpleEvent';

/**
 * The AllOfinlineResponse2005DataScheduleEventsItems model module.
 * @module model/AllOfinlineResponse2005DataScheduleEventsItems
 * @version 1.0.0-alpha-1
 */
export class AllOfinlineResponse2005DataScheduleEventsItems extends SimpleEvent {
  /**
   * Constructs a new <code>AllOfinlineResponse2005DataScheduleEventsItems</code>.
   * @alias module:model/AllOfinlineResponse2005DataScheduleEventsItems
   * @class
   * @extends module:model/SimpleEvent
   * @param startTime {} The time the match started
   * @param blockName {} 
   * @param match {} 
   * @param games {} 
   */
  constructor(startTime, blockName, match, games) {
    super(startTime, blockName, match);
    this.games = games;
    this.match = match;
  }

  /**
   * Constructs a <code>AllOfinlineResponse2005DataScheduleEventsItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfinlineResponse2005DataScheduleEventsItems} obj Optional instance to populate.
   * @return {module:model/AllOfinlineResponse2005DataScheduleEventsItems} The populated <code>AllOfinlineResponse2005DataScheduleEventsItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfinlineResponse2005DataScheduleEventsItems();
      SimpleEvent.constructFromObject(data, obj);
      if (data.hasOwnProperty('games'))
        obj.games = ApiClient.convertToType(data['games'], [Game]);
      if (data.hasOwnProperty('match'))
        obj.match = ApiClient.convertToType(data['match'], Object);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Game>} games
 */
AllOfinlineResponse2005DataScheduleEventsItems.prototype.games = undefined;

/**
 * @member {Object} match
 */
AllOfinlineResponse2005DataScheduleEventsItems.prototype.match = undefined;

