/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ForeignIds} from './ForeignIds';

/**
 * The AllOfhighlanderPlayerForeignIds model module.
 * @module model/AllOfhighlanderPlayerForeignIds
 * @version 1.0.0-alpha-1
 */
export class AllOfhighlanderPlayerForeignIds extends ForeignIds {
  /**
   * Constructs a new <code>AllOfhighlanderPlayerForeignIds</code>.
   * @alias module:model/AllOfhighlanderPlayerForeignIds
   * @class
   * @extends module:model/ForeignIds
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AllOfhighlanderPlayerForeignIds</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfhighlanderPlayerForeignIds} obj Optional instance to populate.
   * @return {module:model/AllOfhighlanderPlayerForeignIds} The populated <code>AllOfhighlanderPlayerForeignIds</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfhighlanderPlayerForeignIds();
      ForeignIds.constructFromObject(data, obj);
    }
    return obj;
  }
}
