/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Record} from './Record';
import {Team} from './Team';
import {TeamId} from './TeamId';
import {TeamSlug} from './TeamSlug';

/**
 * The AllOfrankingTeamsItems model module.
 * @module model/AllOfrankingTeamsItems
 * @version 1.0.0-alpha-1
 */
export class AllOfrankingTeamsItems extends Team {
  /**
   * Constructs a new <code>AllOfrankingTeamsItems</code>.
   * @alias module:model/AllOfrankingTeamsItems
   * @class
   * @extends module:model/Team
   * @param code {} 
   * @param image {} 
   * @param name {} 
   */
  constructor(code, image, name) {
    super(code, image, name);
  }

  /**
   * Constructs a <code>AllOfrankingTeamsItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfrankingTeamsItems} obj Optional instance to populate.
   * @return {module:model/AllOfrankingTeamsItems} The populated <code>AllOfrankingTeamsItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfrankingTeamsItems();
      Team.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = TeamId.constructFromObject(data['id']);
      if (data.hasOwnProperty('slug'))
        obj.slug = TeamSlug.constructFromObject(data['slug']);
      if (data.hasOwnProperty('record'))
        obj.record = Record.constructFromObject(data['record']);
    }
    return obj;
  }
}

/**
 * @member {module:model/TeamId} id
 */
AllOfrankingTeamsItems.prototype.id = undefined;

/**
 * @member {module:model/TeamSlug} slug
 */
AllOfrankingTeamsItems.prototype.slug = undefined;

/**
 * @member {module:model/Record} record
 */
AllOfrankingTeamsItems.prototype.record = undefined;

