/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BaseLeague} from './BaseLeague';
import {EventType} from './EventType';
import {ExtendedEvent} from './ExtendedEvent';
import {State} from './State';

/**
 * The AllOfinlineResponse2001DataScheduleEventsItems model module.
 * @module model/AllOfinlineResponse2001DataScheduleEventsItems
 * @version 1.0.0-alpha-1
 */
export class AllOfinlineResponse2001DataScheduleEventsItems extends ExtendedEvent {
  /**
   * Constructs a new <code>AllOfinlineResponse2001DataScheduleEventsItems</code>.
   * @alias module:model/AllOfinlineResponse2001DataScheduleEventsItems
   * @class
   * @extends module:model/ExtendedEvent
   * @param startTime {} The time the match started
   * @param blockName {} 
   * @param state {} 
   * @param type {} 
   * @param league {} 
   * @param match {} 
   */
  constructor(startTime, blockName, state, type, league, match) {
    super(startTime, blockName, match, state, type);
    this.league = league;
    this.match = match;
  }

  /**
   * Constructs a <code>AllOfinlineResponse2001DataScheduleEventsItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfinlineResponse2001DataScheduleEventsItems} obj Optional instance to populate.
   * @return {module:model/AllOfinlineResponse2001DataScheduleEventsItems} The populated <code>AllOfinlineResponse2001DataScheduleEventsItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfinlineResponse2001DataScheduleEventsItems();
      ExtendedEvent.constructFromObject(data, obj);
      if (data.hasOwnProperty('league'))
        obj.league = BaseLeague.constructFromObject(data['league']);
      if (data.hasOwnProperty('match'))
        obj.match = ApiClient.convertToType(data['match'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/BaseLeague} league
 */
AllOfinlineResponse2001DataScheduleEventsItems.prototype.league = undefined;

/**
 * @member {Object} match
 */
AllOfinlineResponse2001DataScheduleEventsItems.prototype.match = undefined;

