/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ParticipantId} from './ParticipantId';

/**
 * The BaseParticipantStats model module.
 * @module model/BaseParticipantStats
 * @version 1.0.0-alpha-1
 */
export class BaseParticipantStats {
  /**
   * Constructs a new <code>BaseParticipantStats</code>.
   * @alias module:model/BaseParticipantStats
   * @class
   * @param participantId {module:model/ParticipantId} 
   * @param level {Number} 
   * @param kills {Number} 
   * @param deaths {Number} 
   * @param assists {Number} 
   * @param creepScore {Number} 
   */
  constructor(participantId, level, kills, deaths, assists, creepScore) {
    this.participantId = participantId;
    this.level = level;
    this.kills = kills;
    this.deaths = deaths;
    this.assists = assists;
    this.creepScore = creepScore;
  }

  /**
   * Constructs a <code>BaseParticipantStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseParticipantStats} obj Optional instance to populate.
   * @return {module:model/BaseParticipantStats} The populated <code>BaseParticipantStats</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BaseParticipantStats();
      if (data.hasOwnProperty('participantId'))
        obj.participantId = ParticipantId.constructFromObject(data['participantId']);
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'Number');
      if (data.hasOwnProperty('kills'))
        obj.kills = ApiClient.convertToType(data['kills'], 'Number');
      if (data.hasOwnProperty('deaths'))
        obj.deaths = ApiClient.convertToType(data['deaths'], 'Number');
      if (data.hasOwnProperty('assists'))
        obj.assists = ApiClient.convertToType(data['assists'], 'Number');
      if (data.hasOwnProperty('creepScore'))
        obj.creepScore = ApiClient.convertToType(data['creepScore'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/ParticipantId} participantId
 */
BaseParticipantStats.prototype.participantId = undefined;

/**
 * @member {Number} level
 */
BaseParticipantStats.prototype.level = undefined;

/**
 * @member {Number} kills
 */
BaseParticipantStats.prototype.kills = undefined;

/**
 * @member {Number} deaths
 */
BaseParticipantStats.prototype.deaths = undefined;

/**
 * @member {Number} assists
 */
BaseParticipantStats.prototype.assists = undefined;

/**
 * @member {Number} creepScore
 */
BaseParticipantStats.prototype.creepScore = undefined;

