/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BaseLeague model module.
 * @module model/BaseLeague
 * @version 1.0.0-alpha-1
 */
export class BaseLeague {
  /**
   * Constructs a new <code>BaseLeague</code>.
   * @alias module:model/BaseLeague
   * @class
   * @param name {String} The name of the league
   * @param slug {String} URL friendly version of the league's name
   */
  constructor(name, slug) {
    this.name = name;
    this.slug = slug;
  }

  /**
   * Constructs a <code>BaseLeague</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseLeague} obj Optional instance to populate.
   * @return {module:model/BaseLeague} The populated <code>BaseLeague</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BaseLeague();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
    }
    return obj;
  }
}

/**
 * The name of the league
 * @member {String} name
 */
BaseLeague.prototype.name = undefined;

/**
 * URL friendly version of the league's name
 * @member {String} slug
 */
BaseLeague.prototype.slug = undefined;

