/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BaseStrategy model module.
 * @module model/BaseStrategy
 * @version 1.0.0-alpha-1
 */
export class BaseStrategy {
  /**
   * Constructs a new <code>BaseStrategy</code>.
   * @alias module:model/BaseStrategy
   * @class
   * @param count {module:model/BaseStrategy.CountEnum} 
   */
  constructor(count) {
    this.count = count;
  }

  /**
   * Constructs a <code>BaseStrategy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseStrategy} obj Optional instance to populate.
   * @return {module:model/BaseStrategy} The populated <code>BaseStrategy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BaseStrategy();
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>count</code> property.
 * @enum {Number}
 * @readonly
 */
BaseStrategy.CountEnum = {
  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 3
   * @const
   */
  _3: 3,

  /**
   * value: 5
   * @const
   */
  _5: 5
};
/**
 * @member {module:model/BaseStrategy.CountEnum} count
 */
BaseStrategy.prototype.count = undefined;

