/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BracketTypeOptions model module.
 * @module model/BracketTypeOptions
 * @version 1.0.0-alpha-1
 */
export class BracketTypeOptions {
  /**
   * Constructs a new <code>BracketTypeOptions</code>.
   * @alias module:model/BracketTypeOptions
   * @class
   * @param rounds {String} 
   */
  constructor(rounds) {
    this.rounds = rounds;
  }

  /**
   * Constructs a <code>BracketTypeOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BracketTypeOptions} obj Optional instance to populate.
   * @return {module:model/BracketTypeOptions} The populated <code>BracketTypeOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BracketTypeOptions();
      if (data.hasOwnProperty('rounds'))
        obj.rounds = ApiClient.convertToType(data['rounds'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} rounds
 */
BracketTypeOptions.prototype.rounds = undefined;

