/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TeamId} from './TeamId';

/**
 * The CustomTeam model module.
 * @module model/CustomTeam
 * @version 1.0.0-alpha-1
 */
export class CustomTeam {
  /**
   * Constructs a new <code>CustomTeam</code>.
   * @alias module:model/CustomTeam
   * @class
   * @param id {module:model/TeamId} 
   * @param side {module:model/CustomTeam.SideEnum} 
   */
  constructor(id, side) {
    this.id = id;
    this.side = side;
  }

  /**
   * Constructs a <code>CustomTeam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomTeam} obj Optional instance to populate.
   * @return {module:model/CustomTeam} The populated <code>CustomTeam</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CustomTeam();
      if (data.hasOwnProperty('id'))
        obj.id = TeamId.constructFromObject(data['id']);
      if (data.hasOwnProperty('side'))
        obj.side = ApiClient.convertToType(data['side'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/TeamId} id
 */
CustomTeam.prototype.id = undefined;

/**
 * Allowed values for the <code>side</code> property.
 * @enum {String}
 * @readonly
 */
CustomTeam.SideEnum = {
  /**
   * value: "blue"
   * @const
   */
  blue: "blue",

  /**
   * value: "red"
   * @const
   */
  red: "red"
};
/**
 * @member {module:model/CustomTeam.SideEnum} side
 */
CustomTeam.prototype.side = undefined;

