/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HomeLeague} from './HomeLeague';
import {Player} from './Player';
import {Team} from './Team';
import {TeamId} from './TeamId';
import {TeamSlug} from './TeamSlug';

/**
 * The ExtendedTeam model module.
 * @module model/ExtendedTeam
 * @version 1.0.0-alpha-1
 */
export class ExtendedTeam extends Team {
  /**
   * Constructs a new <code>ExtendedTeam</code>.
   * @alias module:model/ExtendedTeam
   * @class
   * @extends module:model/Team
   * @param code {} 
   * @param image {} 
   * @param name {} 
   * @param id {} 
   * @param slug {} 
   * @param alternativeImage {} 
   * @param homeLeague {} 
   * @param players {} 
   */
  constructor(code, image, name, id, slug, alternativeImage, homeLeague, players) {
    super(code, image, name);
    this.id = id;
    this.slug = slug;
    this.alternativeImage = alternativeImage;
    this.homeLeague = homeLeague;
    this.players = players;
  }

  /**
   * Constructs a <code>ExtendedTeam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtendedTeam} obj Optional instance to populate.
   * @return {module:model/ExtendedTeam} The populated <code>ExtendedTeam</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExtendedTeam();
      Team.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = TeamId.constructFromObject(data['id']);
      if (data.hasOwnProperty('slug'))
        obj.slug = TeamSlug.constructFromObject(data['slug']);
      if (data.hasOwnProperty('alternativeImage'))
        obj.alternativeImage = ApiClient.convertToType(data['alternativeImage'], 'String');
      if (data.hasOwnProperty('homeLeague'))
        obj.homeLeague = HomeLeague.constructFromObject(data['homeLeague']);
      if (data.hasOwnProperty('players'))
        obj.players = ApiClient.convertToType(data['players'], [Player]);
    }
    return obj;
  }
}

/**
 * @member {module:model/TeamId} id
 */
ExtendedTeam.prototype.id = undefined;

/**
 * @member {module:model/TeamSlug} slug
 */
ExtendedTeam.prototype.slug = undefined;

/**
 * @member {String} alternativeImage
 */
ExtendedTeam.prototype.alternativeImage = undefined;

/**
 * @member {module:model/HomeLeague} homeLeague
 */
ExtendedTeam.prototype.homeLeague = undefined;

/**
 * @member {Array.<module:model/Player>} players
 */
ExtendedTeam.prototype.players = undefined;

