/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CustomTeam} from './CustomTeam';
import {ExtendedVod} from './ExtendedVod';
import {SimpleGame} from './SimpleGame';
import {State} from './State';

/**
 * The ExtendedGame model module.
 * @module model/ExtendedGame
 * @version 1.0.0-alpha-1
 */
export class ExtendedGame extends SimpleGame {
  /**
   * Constructs a new <code>ExtendedGame</code>.
   * @alias module:model/ExtendedGame
   * @class
   * @extends module:model/SimpleGame
   * @param id {} The game ID
   * @param state {} 
   * @param _number {} The number of the game
   * @param vods {} 
   * @param teams {} 
   */
  constructor(id, state, _number, vods, teams) {
    super(id, state, _number, vods);
    this.teams = teams;
  }

  /**
   * Constructs a <code>ExtendedGame</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtendedGame} obj Optional instance to populate.
   * @return {module:model/ExtendedGame} The populated <code>ExtendedGame</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExtendedGame();
      SimpleGame.constructFromObject(data, obj);
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [CustomTeam]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/CustomTeam>} teams
 */
ExtendedGame.prototype.teams = undefined;

