/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {EventType} from './EventType';
import {SimpleEvent} from './SimpleEvent';
import {State} from './State';

/**
 * The ExtendedEvent model module.
 * @module model/ExtendedEvent
 * @version 1.0.0-alpha-1
 */
export class ExtendedEvent extends SimpleEvent {
  /**
   * Constructs a new <code>ExtendedEvent</code>.
   * @alias module:model/ExtendedEvent
   * @class
   * @extends module:model/SimpleEvent
   * @param startTime {} The time the match started
   * @param blockName {} 
   * @param match {} 
   * @param state {} 
   * @param type {} 
   */
  constructor(startTime, blockName, match, state, type) {
    super(startTime, blockName, match);
    this.state = state;
    this.type = type;
  }

  /**
   * Constructs a <code>ExtendedEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtendedEvent} obj Optional instance to populate.
   * @return {module:model/ExtendedEvent} The populated <code>ExtendedEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExtendedEvent();
      SimpleEvent.constructFromObject(data, obj);
      if (data.hasOwnProperty('state'))
        obj.state = State.constructFromObject(data['state']);
      if (data.hasOwnProperty('type'))
        obj.type = EventType.constructFromObject(data['type']);
    }
    return obj;
  }
}

/**
 * @member {module:model/State} state
 */
ExtendedEvent.prototype.state = undefined;

/**
 * @member {module:model/EventType} type
 */
ExtendedEvent.prototype.type = undefined;

