/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Locale} from './Locale';
import {Vod} from './Vod';

/**
 * The ExtendedVod model module.
 * @module model/ExtendedVod
 * @version 1.0.0-alpha-1
 */
export class ExtendedVod extends Vod {
  /**
   * Constructs a new <code>ExtendedVod</code>.
   * @alias module:model/ExtendedVod
   * @class
   * @extends module:model/Vod
   * @param parameter {} 
   * @param locale {} 
   * @param provider {} The platform that is hosting the vod 
   * @param offset {} Purpose Unknown
   */
  constructor(parameter, locale, provider, offset) {
    super(parameter);
    this.locale = locale;
    this.provider = provider;
    this.offset = offset;
  }

  /**
   * Constructs a <code>ExtendedVod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtendedVod} obj Optional instance to populate.
   * @return {module:model/ExtendedVod} The populated <code>ExtendedVod</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExtendedVod();
      Vod.constructFromObject(data, obj);
      if (data.hasOwnProperty('locale'))
        obj.locale = Locale.constructFromObject(data['locale']);
      if (data.hasOwnProperty('provider'))
        obj.provider = ApiClient.convertToType(data['provider'], 'String');
      if (data.hasOwnProperty('offset'))
        obj.offset = ApiClient.convertToType(data['offset'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/Locale} locale
 */
ExtendedVod.prototype.locale = undefined;

/**
 * Allowed values for the <code>provider</code> property.
 * @enum {String}
 * @readonly
 */
ExtendedVod.ProviderEnum = {
  /**
   * value: "youtube"
   * @const
   */
  youtube: "youtube",

  /**
   * value: "twitch"
   * @const
   */
  twitch: "twitch"
};
/**
 * The platform that is hosting the vod 
 * @member {module:model/ExtendedVod.ProviderEnum} provider
 */
ExtendedVod.prototype.provider = undefined;

/**
 * Purpose Unknown
 * @member {Number} offset
 */
ExtendedVod.prototype.offset = undefined;

