/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SimpleLeague} from './SimpleLeague';

/**
 * The ExtendedLeague model module.
 * @module model/ExtendedLeague
 * @version 1.0.0-alpha-1
 */
export class ExtendedLeague extends SimpleLeague {
  /**
   * Constructs a new <code>ExtendedLeague</code>.
   * @alias module:model/ExtendedLeague
   * @class
   * @extends module:model/SimpleLeague
   * @param slug {} URL friendly version of the league's name
   * @param id {} The league's ID
   * @param image {} URL to an image of the League's logo
   * @param priority {} Unknown
   */
  constructor(slug, id, image, priority) {
    super(name, slug, id, image);
    this.priority = priority;
  }

  /**
   * Constructs a <code>ExtendedLeague</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtendedLeague} obj Optional instance to populate.
   * @return {module:model/ExtendedLeague} The populated <code>ExtendedLeague</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExtendedLeague();
      SimpleLeague.constructFromObject(data, obj);
      if (data.hasOwnProperty('priority'))
        obj.priority = ApiClient.convertToType(data['priority'], 'Number');
    }
    return obj;
  }
}

/**
 * Unknown
 * @member {Number} priority
 */
ExtendedLeague.prototype.priority = undefined;

