/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TeamMetadata} from './TeamMetadata';

/**
 * The GameMetadata model module.
 * @module model/GameMetadata
 * @version 1.0.0-alpha-1
 */
export class GameMetadata {
  /**
   * Constructs a new <code>GameMetadata</code>.
   * @alias module:model/GameMetadata
   * @class
   * @param patchVersion {String} The patch the match was played on
   * @param blueTeamMetadata {module:model/TeamMetadata} 
   * @param redTeamMetadata {module:model/TeamMetadata} 
   */
  constructor(patchVersion, blueTeamMetadata, redTeamMetadata) {
    this.patchVersion = patchVersion;
    this.blueTeamMetadata = blueTeamMetadata;
    this.redTeamMetadata = redTeamMetadata;
  }

  /**
   * Constructs a <code>GameMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameMetadata} obj Optional instance to populate.
   * @return {module:model/GameMetadata} The populated <code>GameMetadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameMetadata();
      if (data.hasOwnProperty('patchVersion'))
        obj.patchVersion = ApiClient.convertToType(data['patchVersion'], 'String');
      if (data.hasOwnProperty('blueTeamMetadata'))
        obj.blueTeamMetadata = TeamMetadata.constructFromObject(data['blueTeamMetadata']);
      if (data.hasOwnProperty('redTeamMetadata'))
        obj.redTeamMetadata = TeamMetadata.constructFromObject(data['redTeamMetadata']);
    }
    return obj;
  }
}

/**
 * The patch the match was played on
 * @member {String} patchVersion
 */
GameMetadata.prototype.patchVersion = undefined;

/**
 * @member {module:model/TeamMetadata} blueTeamMetadata
 */
GameMetadata.prototype.blueTeamMetadata = undefined;

/**
 * @member {module:model/TeamMetadata} redTeamMetadata
 */
GameMetadata.prototype.redTeamMetadata = undefined;

