/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GameMode model module.
 * @module model/GameMode
 * @version 1.0.0-alpha-1
 */
export class GameMode {
  /**
   * Constructs a new <code>GameMode</code>.
   * @alias module:model/GameMode
   * @class
   * @param identifier {module:model/GameMode.IdentifierEnum} 
   * @param requiredPlayers {module:model/GameMode.RequiredPlayersEnum} 
   * @param mapName {module:model/GameMode.MapNameEnum} 
   */
  constructor(identifier, requiredPlayers, mapName) {
    this.identifier = identifier;
    this.requiredPlayers = requiredPlayers;
    this.mapName = mapName;
  }

  /**
   * Constructs a <code>GameMode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameMode} obj Optional instance to populate.
   * @return {module:model/GameMode} The populated <code>GameMode</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameMode();
      if (data.hasOwnProperty('identifier'))
        obj.identifier = ApiClient.convertToType(data['identifier'], 'String');
      if (data.hasOwnProperty('requiredPlayers'))
        obj.requiredPlayers = ApiClient.convertToType(data['requiredPlayers'], 'Number');
      if (data.hasOwnProperty('mapName'))
        obj.mapName = ApiClient.convertToType(data['mapName'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>identifier</code> property.
 * @enum {String}
 * @readonly
 */
GameMode.IdentifierEnum = {
  /**
   * value: "lol:duel"
   * @const
   */
  duel: "lol:duel",

  /**
   * value: "lol:classic"
   * @const
   */
  classic: "lol:classic"
};
/**
 * @member {module:model/GameMode.IdentifierEnum} identifier
 */
GameMode.prototype.identifier = undefined;

/**
 * Allowed values for the <code>requiredPlayers</code> property.
 * @enum {Number}
 * @readonly
 */
GameMode.RequiredPlayersEnum = {
  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 5
   * @const
   */
  _5: 5
};
/**
 * @member {module:model/GameMode.RequiredPlayersEnum} requiredPlayers
 */
GameMode.prototype.requiredPlayers = undefined;

/**
 * Allowed values for the <code>mapName</code> property.
 * @enum {String}
 * @readonly
 */
GameMode.MapNameEnum = {
  /**
   * value: "summoner_rift"
   * @const
   */
  summonerRift: "summoner_rift",

  /**
   * value: "howling_abyss"
   * @const
   */
  howlingAbyss: "howling_abyss"
};
/**
 * @member {module:model/GameMode.MapNameEnum} mapName
 */
GameMode.prototype.mapName = undefined;

