/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GameId model module.
 * @module model/GameId
 * @version 1.0.0-alpha-1
 */
export class GameId {
  /**
   * Constructs a new <code>GameId</code>.
   * The game Id of the match.  It is a [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier) 
   * @alias module:model/GameId
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameId} obj Optional instance to populate.
   * @return {module:model/GameId} The populated <code>GameId</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameId();
    }
    return obj;
  }
}
