/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Vod} from './Vod';

/**
 * The Game model module.
 * @module model/Game
 * @version 1.0.0-alpha-1
 */
export class Game {
  /**
   * Constructs a new <code>Game</code>.
   * @alias module:model/Game
   * @class
   * @param vods {Array.<module:model/Vod>} 
   */
  constructor(vods) {
    this.vods = vods;
  }

  /**
   * Constructs a <code>Game</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Game} obj Optional instance to populate.
   * @return {module:model/Game} The populated <code>Game</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Game();
      if (data.hasOwnProperty('vods'))
        obj.vods = ApiClient.convertToType(data['vods'], [Vod]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Vod>} vods
 */
Game.prototype.vods = undefined;

