/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HighlanderTeam} from './HighlanderTeam';

/**
 * The HighlanderTeams model module.
 * @module model/HighlanderTeams
 * @version 1.0.0-alpha-1
 */
export class HighlanderTeams extends Array {
  /**
   * Constructs a new <code>HighlanderTeams</code>.
   * An array containing the teams that have participated in this league. 
   * @alias module:model/HighlanderTeams
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>HighlanderTeams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HighlanderTeams} obj Optional instance to populate.
   * @return {module:model/HighlanderTeams} The populated <code>HighlanderTeams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HighlanderTeams();
      ApiClient.constructFromObject(data, obj, 'HighlanderTeam');
    }
    return obj;
  }
}
