/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HomeLeague model module.
 * @module model/HomeLeague
 * @version 1.0.0-alpha-1
 */
export class HomeLeague {
  /**
   * Constructs a new <code>HomeLeague</code>.
   * @alias module:model/HomeLeague
   * @class
   * @param name {String} The name of the league
   * @param region {String} The region where the league is located
   */
  constructor(name, region) {
    this.name = name;
    this.region = region;
  }

  /**
   * Constructs a <code>HomeLeague</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HomeLeague} obj Optional instance to populate.
   * @return {module:model/HomeLeague} The populated <code>HomeLeague</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HomeLeague();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
    }
    return obj;
  }
}

/**
 * The name of the league
 * @member {String} name
 */
HomeLeague.prototype.name = undefined;

/**
 * The region where the league is located
 * @member {String} region
 */
HomeLeague.prototype.region = undefined;

