/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2006Data model module.
 * @module model/InlineResponse2006Data
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2006Data {
  /**
   * Constructs a new <code>InlineResponse2006Data</code>.
   * @alias module:model/InlineResponse2006Data
   * @class
   * @param event {Object} 
   */
  constructor(event) {
    this.event = event;
  }

  /**
   * Constructs a <code>InlineResponse2006Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2006Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2006Data} The populated <code>InlineResponse2006Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2006Data();
      if (data.hasOwnProperty('event'))
        obj.event = ApiClient.convertToType(data['event'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} event
 */
InlineResponse2006Data.prototype.event = undefined;

