/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Stage} from './Stage';

/**
 * The InlineResponse2004DataStandings model module.
 * @module model/InlineResponse2004DataStandings
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2004DataStandings {
  /**
   * Constructs a new <code>InlineResponse2004DataStandings</code>.
   * @alias module:model/InlineResponse2004DataStandings
   * @class
   * @param stages {Array.<module:model/Stage>} 
   */
  constructor(stages) {
    this.stages = stages;
  }

  /**
   * Constructs a <code>InlineResponse2004DataStandings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2004DataStandings} obj Optional instance to populate.
   * @return {module:model/InlineResponse2004DataStandings} The populated <code>InlineResponse2004DataStandings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2004DataStandings();
      if (data.hasOwnProperty('stages'))
        obj.stages = ApiClient.convertToType(data['stages'], [Stage]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Stage>} stages
 */
InlineResponse2004DataStandings.prototype.stages = undefined;

