/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20014TeamStatsHistories model module.
 * @module model/InlineResponse20014TeamStatsHistories
 * @version 1.0.0-alpha-1
 */
export class InlineResponse20014TeamStatsHistories {
  /**
   * Constructs a new <code>InlineResponse20014TeamStatsHistories</code>.
   * @alias module:model/InlineResponse20014TeamStatsHistories
   * @class
   * @param id {String} Contains the game ID and the team ID.
   * @param timestamp {Number} Unix timestamp in milliseconds of when the match started.
   * @param assists {Number} 
   * @param kills {Number} 
   * @param win {Boolean} 
   * @param match {String} The match ID
   * @param team {Number} The team ID
   * @param opponent {Number} The opponent's team ID
   * @param game {Number} The game ID
   */
  constructor(id, timestamp, assists, kills, win, match, team, opponent, game) {
    this.id = id;
    this.timestamp = timestamp;
    this.assists = assists;
    this.kills = kills;
    this.win = win;
    this.match = match;
    this.team = team;
    this.opponent = opponent;
    this.game = game;
  }

  /**
   * Constructs a <code>InlineResponse20014TeamStatsHistories</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20014TeamStatsHistories} obj Optional instance to populate.
   * @return {module:model/InlineResponse20014TeamStatsHistories} The populated <code>InlineResponse20014TeamStatsHistories</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20014TeamStatsHistories();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('assists'))
        obj.assists = ApiClient.convertToType(data['assists'], 'Number');
      if (data.hasOwnProperty('kills'))
        obj.kills = ApiClient.convertToType(data['kills'], 'Number');
      if (data.hasOwnProperty('win'))
        obj.win = ApiClient.convertToType(data['win'], 'Boolean');
      if (data.hasOwnProperty('championIds'))
        obj.championIds = ApiClient.convertToType(data['championIds'], ['Number']);
      if (data.hasOwnProperty('match'))
        obj.match = ApiClient.convertToType(data['match'], 'String');
      if (data.hasOwnProperty('team'))
        obj.team = ApiClient.convertToType(data['team'], 'Number');
      if (data.hasOwnProperty('opponent'))
        obj.opponent = ApiClient.convertToType(data['opponent'], 'Number');
      if (data.hasOwnProperty('game'))
        obj.game = ApiClient.convertToType(data['game'], 'Number');
    }
    return obj;
  }
}

/**
 * Contains the game ID and the team ID.
 * @member {String} id
 */
InlineResponse20014TeamStatsHistories.prototype.id = undefined;

/**
 * Unix timestamp in milliseconds of when the match started.
 * @member {Number} timestamp
 */
InlineResponse20014TeamStatsHistories.prototype.timestamp = undefined;

/**
 * @member {Number} assists
 */
InlineResponse20014TeamStatsHistories.prototype.assists = undefined;

/**
 * @member {Number} kills
 */
InlineResponse20014TeamStatsHistories.prototype.kills = undefined;

/**
 * @member {Boolean} win
 */
InlineResponse20014TeamStatsHistories.prototype.win = undefined;

/**
 * @member {Array.<Number>} championIds
 */
InlineResponse20014TeamStatsHistories.prototype.championIds = undefined;

/**
 * The match ID
 * @member {String} match
 */
InlineResponse20014TeamStatsHistories.prototype.match = undefined;

/**
 * The team ID
 * @member {Number} team
 */
InlineResponse20014TeamStatsHistories.prototype.team = undefined;

/**
 * The opponent's team ID
 * @member {Number} opponent
 */
InlineResponse20014TeamStatsHistories.prototype.opponent = undefined;

/**
 * The game ID
 * @member {Number} game
 */
InlineResponse20014TeamStatsHistories.prototype.game = undefined;

