/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HighlanderTeams} from './HighlanderTeams';
import {HighlanderTournaments} from './HighlanderTournaments';
import {InlineResponse20014TeamRosterStats} from './InlineResponse20014TeamRosterStats';
import {InlineResponse20014TeamStatsHistories} from './InlineResponse20014TeamStatsHistories';
import {InlineResponse20014TeamStatsSummaries} from './InlineResponse20014TeamStatsSummaries';
import {ScheduleItem} from './ScheduleItem';
import {AllOfinlineResponse20014PlayersItems} from './AllOfinlineResponse20014PlayersItems';

/**
 * The InlineResponse20014 model module.
 * @module model/InlineResponse20014
 * @version 1.0.0-alpha-1
 */
export class InlineResponse20014 {
  /**
   * Constructs a new <code>InlineResponse20014</code>.
   * @alias module:model/InlineResponse20014
   * @class
   * @param players {Array.<Object>} Contains the players currently in the team.
   * @param highlanderTournaments {module:model/HighlanderTournaments} 
   * @param scheduleItems {Array.<module:model/ScheduleItem>} Contains details about a few of the team's upcoming matches
   * @param teams {module:model/HighlanderTeams} 
   */
  constructor(players, highlanderTournaments, scheduleItems, teams) {
    this.players = players;
    this.highlanderTournaments = highlanderTournaments;
    this.scheduleItems = scheduleItems;
    this.teams = teams;
  }

  /**
   * Constructs a <code>InlineResponse20014</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20014} obj Optional instance to populate.
   * @return {module:model/InlineResponse20014} The populated <code>InlineResponse20014</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20014();
      if (data.hasOwnProperty('players'))
        obj.players = ApiClient.convertToType(data['players'], [AllOfinlineResponse20014PlayersItems]);
      if (data.hasOwnProperty('highlanderTournaments'))
        obj.highlanderTournaments = HighlanderTournaments.constructFromObject(data['highlanderTournaments']);
      if (data.hasOwnProperty('scheduleItems'))
        obj.scheduleItems = ApiClient.convertToType(data['scheduleItems'], [ScheduleItem]);
      if (data.hasOwnProperty('teamStatsSummaries'))
        obj.teamStatsSummaries = ApiClient.convertToType(data['teamStatsSummaries'], [InlineResponse20014TeamStatsSummaries]);
      if (data.hasOwnProperty('teamRosterStats'))
        obj.teamRosterStats = ApiClient.convertToType(data['teamRosterStats'], [InlineResponse20014TeamRosterStats]);
      if (data.hasOwnProperty('teamStatsHistories'))
        obj.teamStatsHistories = ApiClient.convertToType(data['teamStatsHistories'], [InlineResponse20014TeamStatsHistories]);
      if (data.hasOwnProperty('teams'))
        obj.teams = HighlanderTeams.constructFromObject(data['teams']);
    }
    return obj;
  }
}

/**
 * Contains the players currently in the team.
 * @member {Array.<Object>} players
 */
InlineResponse20014.prototype.players = undefined;

/**
 * @member {module:model/HighlanderTournaments} highlanderTournaments
 */
InlineResponse20014.prototype.highlanderTournaments = undefined;

/**
 * Contains details about a few of the team's upcoming matches
 * @member {Array.<module:model/ScheduleItem>} scheduleItems
 */
InlineResponse20014.prototype.scheduleItems = undefined;

/**
 * Contains a summary of the team stats during that particular tournament. 
 * @member {Array.<module:model/InlineResponse20014TeamStatsSummaries>} teamStatsSummaries
 */
InlineResponse20014.prototype.teamStatsSummaries = undefined;

/**
 * Contains stats of the players of the particular team who played in that tournament. 
 * @member {Array.<module:model/InlineResponse20014TeamRosterStats>} teamRosterStats
 */
InlineResponse20014.prototype.teamRosterStats = undefined;

/**
 * A contains stats of the team's previous 4 matches in that particular tournament. 
 * @member {Array.<module:model/InlineResponse20014TeamStatsHistories>} teamStatsHistories
 */
InlineResponse20014.prototype.teamStatsHistories = undefined;

/**
 * @member {module:model/HighlanderTeams} teams
 */
InlineResponse20014.prototype.teams = undefined;

