/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse2001DataSchedulePages} from './InlineResponse2001DataSchedulePages';
import {AllOfinlineResponse2001DataScheduleEventsItems} from './AllOfinlineResponse2001DataScheduleEventsItems';

/**
 * The InlineResponse2001DataSchedule model module.
 * @module model/InlineResponse2001DataSchedule
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2001DataSchedule {
  /**
   * Constructs a new <code>InlineResponse2001DataSchedule</code>.
   * @alias module:model/InlineResponse2001DataSchedule
   * @class
   * @param updated {Date} The time the data presented was last updated
   * @param pages {module:model/InlineResponse2001DataSchedulePages} 
   * @param events {Array.<Object>} 
   */
  constructor(updated, pages, events) {
    this.updated = updated;
    this.pages = pages;
    this.events = events;
  }

  /**
   * Constructs a <code>InlineResponse2001DataSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001DataSchedule} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001DataSchedule} The populated <code>InlineResponse2001DataSchedule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001DataSchedule();
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('pages'))
        obj.pages = InlineResponse2001DataSchedulePages.constructFromObject(data['pages']);
      if (data.hasOwnProperty('events'))
        obj.events = ApiClient.convertToType(data['events'], [AllOfinlineResponse2001DataScheduleEventsItems]);
    }
    return obj;
  }
}

/**
 * The time the data presented was last updated
 * @member {Date} updated
 */
InlineResponse2001DataSchedule.prototype.updated = undefined;

/**
 * @member {module:model/InlineResponse2001DataSchedulePages} pages
 */
InlineResponse2001DataSchedule.prototype.pages = undefined;

/**
 * @member {Array.<Object>} events
 */
InlineResponse2001DataSchedule.prototype.events = undefined;

