/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PageToken} from './PageToken';

/**
 * The InlineResponse2001DataSchedulePages model module.
 * @module model/InlineResponse2001DataSchedulePages
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2001DataSchedulePages {
  /**
   * Constructs a new <code>InlineResponse2001DataSchedulePages</code>.
   * @alias module:model/InlineResponse2001DataSchedulePages
   * @class
   * @param older {module:model/PageToken} 
   * @param newer {module:model/PageToken} 
   */
  constructor(older, newer) {
    this.older = older;
    this.newer = newer;
  }

  /**
   * Constructs a <code>InlineResponse2001DataSchedulePages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001DataSchedulePages} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001DataSchedulePages} The populated <code>InlineResponse2001DataSchedulePages</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001DataSchedulePages();
      if (data.hasOwnProperty('older'))
        obj.older = PageToken.constructFromObject(data['older']);
      if (data.hasOwnProperty('newer'))
        obj.newer = PageToken.constructFromObject(data['newer']);
    }
    return obj;
  }
}

/**
 * @member {module:model/PageToken} older
 */
InlineResponse2001DataSchedulePages.prototype.older = undefined;

/**
 * @member {module:model/PageToken} newer
 */
InlineResponse2001DataSchedulePages.prototype.newer = undefined;

