/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HighlanderLeague} from './HighlanderLeague';
import {NavItem} from './NavItem';

/**
 * The InlineResponse20010 model module.
 * @module model/InlineResponse20010
 * @version 1.0.0-alpha-1
 */
export class InlineResponse20010 {
  /**
   * Constructs a new <code>InlineResponse20010</code>.
   * @alias module:model/InlineResponse20010
   * @class
   * @param navItems {Array.<module:model/NavItem>} 
   * @param leagues {Array.<module:model/HighlanderLeague>} 
   */
  constructor(navItems, leagues) {
    this.navItems = navItems;
    this.leagues = leagues;
  }

  /**
   * Constructs a <code>InlineResponse20010</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20010} obj Optional instance to populate.
   * @return {module:model/InlineResponse20010} The populated <code>InlineResponse20010</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20010();
      if (data.hasOwnProperty('navItems'))
        obj.navItems = ApiClient.convertToType(data['navItems'], [NavItem]);
      if (data.hasOwnProperty('leagues'))
        obj.leagues = ApiClient.convertToType(data['leagues'], [HighlanderLeague]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/NavItem>} navItems
 */
InlineResponse20010.prototype.navItems = undefined;

/**
 * @member {Array.<module:model/HighlanderLeague>} leagues
 */
InlineResponse20010.prototype.leagues = undefined;

