/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2002DataSchedule model module.
 * @module model/InlineResponse2002DataSchedule
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2002DataSchedule {
  /**
   * Constructs a new <code>InlineResponse2002DataSchedule</code>.
   * @alias module:model/InlineResponse2002DataSchedule
   * @class
   * @param events {Array.<Object>} Array of event objects representing matches that are currently ongoing.  This will be null if no match is taking place at that time 
   */
  constructor(events) {
    this.events = events;
  }

  /**
   * Constructs a <code>InlineResponse2002DataSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002DataSchedule} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002DataSchedule} The populated <code>InlineResponse2002DataSchedule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002DataSchedule();
      if (data.hasOwnProperty('events'))
        obj.events = ApiClient.convertToType(data['events'], [AllOfinlineResponse2002DataScheduleEventsItems]);
    }
    return obj;
  }
}

/**
 * Array of event objects representing matches that are currently ongoing.  This will be null if no match is taking place at that time 
 * @member {Array.<Object>} events
 */
InlineResponse2002DataSchedule.prototype.events = undefined;

