/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse4041 model module.
 * @module model/InlineResponse4041
 * @version 1.0.0-alpha-1
 */
export class InlineResponse4041 {
  /**
   * Constructs a new <code>InlineResponse4041</code>.
   * @alias module:model/InlineResponse4041
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse4041</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse4041} obj Optional instance to populate.
   * @return {module:model/InlineResponse4041} The populated <code>InlineResponse4041</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse4041();
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>error</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse4041.ErrorEnum = {
  /**
   * value: "Invalid Input Error"
   * @const
   */
  invalidInputError: "Invalid Input Error"
};
/**
 * @member {module:model/InlineResponse4041.ErrorEnum} error
 */
InlineResponse4041.prototype.error = undefined;

