/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse2003DataLeagues} from './InlineResponse2003DataLeagues';

/**
 * The InlineResponse2003Data model module.
 * @module model/InlineResponse2003Data
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2003Data {
  /**
   * Constructs a new <code>InlineResponse2003Data</code>.
   * @alias module:model/InlineResponse2003Data
   * @class
   * @param leagues {Array.<module:model/InlineResponse2003DataLeagues>} An array of league object(s) where each object contains an array of tournaments. 
   */
  constructor(leagues) {
    this.leagues = leagues;
  }

  /**
   * Constructs a <code>InlineResponse2003Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003Data} The populated <code>InlineResponse2003Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2003Data();
      if (data.hasOwnProperty('leagues'))
        obj.leagues = ApiClient.convertToType(data['leagues'], [InlineResponse2003DataLeagues]);
    }
    return obj;
  }
}

/**
 * An array of league object(s) where each object contains an array of tournaments. 
 * @member {Array.<module:model/InlineResponse2003DataLeagues>} leagues
 */
InlineResponse2003Data.prototype.leagues = undefined;

