/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AllOfinlineResponse2005DataScheduleEventsItems} from './AllOfinlineResponse2005DataScheduleEventsItems';

/**
 * The InlineResponse2005DataSchedule model module.
 * @module model/InlineResponse2005DataSchedule
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2005DataSchedule {
  /**
   * Constructs a new <code>InlineResponse2005DataSchedule</code>.
   * @alias module:model/InlineResponse2005DataSchedule
   * @class
   * @param events {Array.<Object>} 
   */
  constructor(events) {
    this.events = events;
  }

  /**
   * Constructs a <code>InlineResponse2005DataSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2005DataSchedule} obj Optional instance to populate.
   * @return {module:model/InlineResponse2005DataSchedule} The populated <code>InlineResponse2005DataSchedule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2005DataSchedule();
      if (data.hasOwnProperty('events'))
        obj.events = ApiClient.convertToType(data['events'], [AllOfinlineResponse2005DataScheduleEventsItems]);
    }
    return obj;
  }
}

/**
 * @member {Array.<Object>} events
 */
InlineResponse2005DataSchedule.prototype.events = undefined;

