/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HighlanderPlayers} from './HighlanderPlayers';
import {HighlanderRecords} from './HighlanderRecords';
import {HighlanderTeams} from './HighlanderTeams';
import {HighlanderTournaments} from './HighlanderTournaments';
import {ScheduleItem} from './ScheduleItem';

/**
 * The InlineResponse20013 model module.
 * @module model/InlineResponse20013
 * @version 1.0.0-alpha-1
 */
export class InlineResponse20013 {
  /**
   * Constructs a new <code>InlineResponse20013</code>.
   * @alias module:model/InlineResponse20013
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20013</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20013} obj Optional instance to populate.
   * @return {module:model/InlineResponse20013} The populated <code>InlineResponse20013</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20013();
      if (data.hasOwnProperty('scheduleItems'))
        obj.scheduleItems = ApiClient.convertToType(data['scheduleItems'], [ScheduleItem]);
      if (data.hasOwnProperty('highlanderTournaments'))
        obj.highlanderTournaments = HighlanderTournaments.constructFromObject(data['highlanderTournaments']);
      if (data.hasOwnProperty('teams'))
        obj.teams = HighlanderTeams.constructFromObject(data['teams']);
      if (data.hasOwnProperty('highlanderRecords'))
        obj.highlanderRecords = HighlanderRecords.constructFromObject(data['highlanderRecords']);
      if (data.hasOwnProperty('players'))
        obj.players = HighlanderPlayers.constructFromObject(data['players']);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ScheduleItem>} scheduleItems
 */
InlineResponse20013.prototype.scheduleItems = undefined;

/**
 * @member {module:model/HighlanderTournaments} highlanderTournaments
 */
InlineResponse20013.prototype.highlanderTournaments = undefined;

/**
 * @member {module:model/HighlanderTeams} teams
 */
InlineResponse20013.prototype.teams = undefined;

/**
 * @member {module:model/HighlanderRecords} highlanderRecords
 */
InlineResponse20013.prototype.highlanderRecords = undefined;

/**
 * @member {module:model/HighlanderPlayers} players
 */
InlineResponse20013.prototype.players = undefined;

