/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse20015Mostplayedchampions} from './InlineResponse20015Mostplayedchampions';

/**
 * The InlineResponse20015PlayerStatsSummaries model module.
 * @module model/InlineResponse20015PlayerStatsSummaries
 * @version 1.0.0-alpha-1
 */
export class InlineResponse20015PlayerStatsSummaries {
  /**
   * Constructs a new <code>InlineResponse20015PlayerStatsSummaries</code>.
   * @alias module:model/InlineResponse20015PlayerStatsSummaries
   * @class
   * @param playerId {String} 
   * @param kdaRatio {Number} 
   * @param kdaRatioRank {Number} 
   * @param csPerTenMinutes {Number} 
   * @param csPerTenMinutesRank {Number} 
   * @param killParticipation {Number} 
   * @param killParticipationRank {Number} 
   * @param mostplayedchampions {Array.<module:model/InlineResponse20015Mostplayedchampions>} 
   */
  constructor(playerId, kdaRatio, kdaRatioRank, csPerTenMinutes, csPerTenMinutesRank, killParticipation, killParticipationRank, mostplayedchampions) {
    this.playerId = playerId;
    this.kdaRatio = kdaRatio;
    this.kdaRatioRank = kdaRatioRank;
    this.csPerTenMinutes = csPerTenMinutes;
    this.csPerTenMinutesRank = csPerTenMinutesRank;
    this.killParticipation = killParticipation;
    this.killParticipationRank = killParticipationRank;
    this.mostplayedchampions = mostplayedchampions;
  }

  /**
   * Constructs a <code>InlineResponse20015PlayerStatsSummaries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20015PlayerStatsSummaries} obj Optional instance to populate.
   * @return {module:model/InlineResponse20015PlayerStatsSummaries} The populated <code>InlineResponse20015PlayerStatsSummaries</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20015PlayerStatsSummaries();
      if (data.hasOwnProperty('playerId'))
        obj.playerId = ApiClient.convertToType(data['playerId'], 'String');
      if (data.hasOwnProperty('kdaRatio'))
        obj.kdaRatio = ApiClient.convertToType(data['kdaRatio'], 'Number');
      if (data.hasOwnProperty('kdaRatioRank'))
        obj.kdaRatioRank = ApiClient.convertToType(data['kdaRatioRank'], 'Number');
      if (data.hasOwnProperty('csPerTenMinutes'))
        obj.csPerTenMinutes = ApiClient.convertToType(data['csPerTenMinutes'], 'Number');
      if (data.hasOwnProperty('csPerTenMinutesRank'))
        obj.csPerTenMinutesRank = ApiClient.convertToType(data['csPerTenMinutesRank'], 'Number');
      if (data.hasOwnProperty('killParticipation'))
        obj.killParticipation = ApiClient.convertToType(data['killParticipation'], 'Number');
      if (data.hasOwnProperty('killParticipationRank'))
        obj.killParticipationRank = ApiClient.convertToType(data['killParticipationRank'], 'Number');
      if (data.hasOwnProperty('mostplayedchampions'))
        obj.mostplayedchampions = ApiClient.convertToType(data['mostplayedchampions'], [InlineResponse20015Mostplayedchampions]);
    }
    return obj;
  }
}

/**
 * @member {String} playerId
 */
InlineResponse20015PlayerStatsSummaries.prototype.playerId = undefined;

/**
 * @member {Number} kdaRatio
 */
InlineResponse20015PlayerStatsSummaries.prototype.kdaRatio = undefined;

/**
 * @member {Number} kdaRatioRank
 */
InlineResponse20015PlayerStatsSummaries.prototype.kdaRatioRank = undefined;

/**
 * @member {Number} csPerTenMinutes
 */
InlineResponse20015PlayerStatsSummaries.prototype.csPerTenMinutes = undefined;

/**
 * @member {Number} csPerTenMinutesRank
 */
InlineResponse20015PlayerStatsSummaries.prototype.csPerTenMinutesRank = undefined;

/**
 * @member {Number} killParticipation
 */
InlineResponse20015PlayerStatsSummaries.prototype.killParticipation = undefined;

/**
 * @member {Number} killParticipationRank
 */
InlineResponse20015PlayerStatsSummaries.prototype.killParticipationRank = undefined;

/**
 * @member {Array.<module:model/InlineResponse20015Mostplayedchampions>} mostplayedchampions
 */
InlineResponse20015PlayerStatsSummaries.prototype.mostplayedchampions = undefined;

