/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20014AverageDamageByPosition model module.
 * @module model/InlineResponse20014AverageDamageByPosition
 * @version 1.0.0-alpha-1
 */
export class InlineResponse20014AverageDamageByPosition {
  /**
   * Constructs a new <code>InlineResponse20014AverageDamageByPosition</code>.
   * It is assumed that the values represent the damage dealt in thousands. 
   * @alias module:model/InlineResponse20014AverageDamageByPosition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20014AverageDamageByPosition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20014AverageDamageByPosition} obj Optional instance to populate.
   * @return {module:model/InlineResponse20014AverageDamageByPosition} The populated <code>InlineResponse20014AverageDamageByPosition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20014AverageDamageByPosition();
      if (data.hasOwnProperty('DUO_CARRY'))
        obj.DUO_CARRY = ApiClient.convertToType(data['DUO_CARRY'], 'Number');
      if (data.hasOwnProperty('DUO_SUPPORT'))
        obj.DUO_SUPPORT = ApiClient.convertToType(data['DUO_SUPPORT'], 'Number');
      if (data.hasOwnProperty('SOLO'))
        obj.SOLO = ApiClient.convertToType(data['SOLO'], 'Number');
      if (data.hasOwnProperty('NONE'))
        obj.NONE = ApiClient.convertToType(data['NONE'], 'Number');
      if (data.hasOwnProperty('DUO'))
        obj.DUO = ApiClient.convertToType(data['DUO'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} DUO_CARRY
 */
InlineResponse20014AverageDamageByPosition.prototype.DUO_CARRY = undefined;

/**
 * @member {Number} DUO_SUPPORT
 */
InlineResponse20014AverageDamageByPosition.prototype.DUO_SUPPORT = undefined;

/**
 * @member {Number} SOLO
 */
InlineResponse20014AverageDamageByPosition.prototype.SOLO = undefined;

/**
 * @member {Number} NONE
 */
InlineResponse20014AverageDamageByPosition.prototype.NONE = undefined;

/**
 * @member {Number} DUO
 */
InlineResponse20014AverageDamageByPosition.prototype.DUO = undefined;

