/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ExtendedTeam} from './ExtendedTeam';

/**
 * The InlineResponse2007Data model module.
 * @module model/InlineResponse2007Data
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2007Data {
  /**
   * Constructs a new <code>InlineResponse2007Data</code>.
   * @alias module:model/InlineResponse2007Data
   * @class
   * @param teams {Array.<module:model/ExtendedTeam>} 
   */
  constructor(teams) {
    this.teams = teams;
  }

  /**
   * Constructs a <code>InlineResponse2007Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007Data} The populated <code>InlineResponse2007Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2007Data();
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [ExtendedTeam]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ExtendedTeam>} teams
 */
InlineResponse2007Data.prototype.teams = undefined;

