/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20015PlayerStatsHistories model module.
 * @module model/InlineResponse20015PlayerStatsHistories
 * @version 1.0.0-alpha-1
 */
export class InlineResponse20015PlayerStatsHistories {
  /**
   * Constructs a new <code>InlineResponse20015PlayerStatsHistories</code>.
   * @alias module:model/InlineResponse20015PlayerStatsHistories
   * @class
   * @param id {String} 
   * @param playerId {String} 
   * @param championId {Number} 
   * @param timestamp {Number} Unix timestamp in milliseconds of when the match started.
   * @param assists {Number} 
   * @param deaths {Number} 
   * @param kills {Number} 
   * @param csPerTenMinutes {Number} 
   * @param kdaRatio {Number} 
   * @param killParticipation {Number} 
   * @param win {Boolean} 
   * @param match {String} The match ID
   * @param team {Number} The team ID the player playes for.
   * @param opponent {Number} The opponent's team ID.
   * @param game {String} The game ID
   */
  constructor(id, playerId, championId, timestamp, assists, deaths, kills, csPerTenMinutes, kdaRatio, killParticipation, win, match, team, opponent, game) {
    this.id = id;
    this.playerId = playerId;
    this.championId = championId;
    this.timestamp = timestamp;
    this.assists = assists;
    this.deaths = deaths;
    this.kills = kills;
    this.csPerTenMinutes = csPerTenMinutes;
    this.kdaRatio = kdaRatio;
    this.killParticipation = killParticipation;
    this.win = win;
    this.match = match;
    this.team = team;
    this.opponent = opponent;
    this.game = game;
  }

  /**
   * Constructs a <code>InlineResponse20015PlayerStatsHistories</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20015PlayerStatsHistories} obj Optional instance to populate.
   * @return {module:model/InlineResponse20015PlayerStatsHistories} The populated <code>InlineResponse20015PlayerStatsHistories</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20015PlayerStatsHistories();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('playerId'))
        obj.playerId = ApiClient.convertToType(data['playerId'], 'String');
      if (data.hasOwnProperty('championId'))
        obj.championId = ApiClient.convertToType(data['championId'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('assists'))
        obj.assists = ApiClient.convertToType(data['assists'], 'Number');
      if (data.hasOwnProperty('deaths'))
        obj.deaths = ApiClient.convertToType(data['deaths'], 'Number');
      if (data.hasOwnProperty('kills'))
        obj.kills = ApiClient.convertToType(data['kills'], 'Number');
      if (data.hasOwnProperty('csPerTenMinutes'))
        obj.csPerTenMinutes = ApiClient.convertToType(data['csPerTenMinutes'], 'Number');
      if (data.hasOwnProperty('kdaRatio'))
        obj.kdaRatio = ApiClient.convertToType(data['kdaRatio'], 'Number');
      if (data.hasOwnProperty('killParticipation'))
        obj.killParticipation = ApiClient.convertToType(data['killParticipation'], 'Number');
      if (data.hasOwnProperty('win'))
        obj.win = ApiClient.convertToType(data['win'], 'Boolean');
      if (data.hasOwnProperty('match'))
        obj.match = ApiClient.convertToType(data['match'], 'String');
      if (data.hasOwnProperty('team'))
        obj.team = ApiClient.convertToType(data['team'], 'Number');
      if (data.hasOwnProperty('opponent'))
        obj.opponent = ApiClient.convertToType(data['opponent'], 'Number');
      if (data.hasOwnProperty('game'))
        obj.game = ApiClient.convertToType(data['game'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
InlineResponse20015PlayerStatsHistories.prototype.id = undefined;

/**
 * @member {String} playerId
 */
InlineResponse20015PlayerStatsHistories.prototype.playerId = undefined;

/**
 * @member {Number} championId
 */
InlineResponse20015PlayerStatsHistories.prototype.championId = undefined;

/**
 * Unix timestamp in milliseconds of when the match started.
 * @member {Number} timestamp
 */
InlineResponse20015PlayerStatsHistories.prototype.timestamp = undefined;

/**
 * @member {Number} assists
 */
InlineResponse20015PlayerStatsHistories.prototype.assists = undefined;

/**
 * @member {Number} deaths
 */
InlineResponse20015PlayerStatsHistories.prototype.deaths = undefined;

/**
 * @member {Number} kills
 */
InlineResponse20015PlayerStatsHistories.prototype.kills = undefined;

/**
 * @member {Number} csPerTenMinutes
 */
InlineResponse20015PlayerStatsHistories.prototype.csPerTenMinutes = undefined;

/**
 * @member {Number} kdaRatio
 */
InlineResponse20015PlayerStatsHistories.prototype.kdaRatio = undefined;

/**
 * @member {Number} killParticipation
 */
InlineResponse20015PlayerStatsHistories.prototype.killParticipation = undefined;

/**
 * @member {Boolean} win
 */
InlineResponse20015PlayerStatsHistories.prototype.win = undefined;

/**
 * The match ID
 * @member {String} match
 */
InlineResponse20015PlayerStatsHistories.prototype.match = undefined;

/**
 * The team ID the player playes for.
 * @member {Number} team
 */
InlineResponse20015PlayerStatsHistories.prototype.team = undefined;

/**
 * The opponent's team ID.
 * @member {Number} opponent
 */
InlineResponse20015PlayerStatsHistories.prototype.opponent = undefined;

/**
 * The game ID
 * @member {String} game
 */
InlineResponse20015PlayerStatsHistories.prototype.game = undefined;

