/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Tournament} from './Tournament';

/**
 * The InlineResponse2003DataLeagues model module.
 * @module model/InlineResponse2003DataLeagues
 * @version 1.0.0-alpha-1
 */
export class InlineResponse2003DataLeagues {
  /**
   * Constructs a new <code>InlineResponse2003DataLeagues</code>.
   * @alias module:model/InlineResponse2003DataLeagues
   * @class
   * @param tournaments {Array.<module:model/Tournament>} An array of tournament object(s) where each object describes a specific tournament. 
   */
  constructor(tournaments) {
    this.tournaments = tournaments;
  }

  /**
   * Constructs a <code>InlineResponse2003DataLeagues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003DataLeagues} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003DataLeagues} The populated <code>InlineResponse2003DataLeagues</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2003DataLeagues();
      if (data.hasOwnProperty('tournaments'))
        obj.tournaments = ApiClient.convertToType(data['tournaments'], [Tournament]);
    }
    return obj;
  }
}

/**
 * An array of tournament object(s) where each object describes a specific tournament. 
 * @member {Array.<module:model/Tournament>} tournaments
 */
InlineResponse2003DataLeagues.prototype.tournaments = undefined;

