/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse404Error model module.
 * @module model/InlineResponse404Error
 * @version 1.0.0-alpha-1
 */
export class InlineResponse404Error {
  /**
   * Constructs a new <code>InlineResponse404Error</code>.
   * @alias module:model/InlineResponse404Error
   * @class
   * @param statusCode {module:model/InlineResponse404Error.StatusCodeEnum} 
   * @param message {String} 
   */
  constructor(statusCode, message) {
    this.statusCode = statusCode;
    this.message = message;
  }

  /**
   * Constructs a <code>InlineResponse404Error</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse404Error} obj Optional instance to populate.
   * @return {module:model/InlineResponse404Error} The populated <code>InlineResponse404Error</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse404Error();
      if (data.hasOwnProperty('statusCode'))
        obj.statusCode = ApiClient.convertToType(data['statusCode'], 'Number');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>statusCode</code> property.
 * @enum {Number}
 * @readonly
 */
InlineResponse404Error.StatusCodeEnum = {
  /**
   * value: 404
   * @const
   */
  _404: 404
};
/**
 * @member {module:model/InlineResponse404Error.StatusCodeEnum} statusCode
 */
InlineResponse404Error.prototype.statusCode = undefined;

/**
 * @member {String} message
 */
InlineResponse404Error.prototype.message = undefined;

