/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NavItem model module.
 * @module model/NavItem
 * @version 1.0.0-alpha-1
 */
export class NavItem {
  /**
   * Constructs a new <code>NavItem</code>.
   * @alias module:model/NavItem
   * @class
   * @param id {Number} 
   * @param link {String} 
   * @param slug {String} 
   * @param label {String} 
   * @param imageUrl {String} 
   * @param order {Number} 
   * @param external {Boolean} 
   * @param parentNavItem {Object} 
   * @param createdAt {Date} The date and time when this entry was created.
   * @param updatedAt {Date} The date and time when this entry was last updated.
   */
  constructor(id, link, slug, label, imageUrl, order, external, parentNavItem, createdAt, updatedAt) {
    this.id = id;
    this.link = link;
    this.slug = slug;
    this.label = label;
    this.imageUrl = imageUrl;
    this.order = order;
    this.external = external;
    this.parentNavItem = parentNavItem;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Constructs a <code>NavItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NavItem} obj Optional instance to populate.
   * @return {module:model/NavItem} The populated <code>NavItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NavItem();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('imageUrl'))
        obj.imageUrl = ApiClient.convertToType(data['imageUrl'], 'String');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
      if (data.hasOwnProperty('external'))
        obj.external = ApiClient.convertToType(data['external'], 'Boolean');
      if (data.hasOwnProperty('parentNavItem'))
        obj.parentNavItem = ApiClient.convertToType(data['parentNavItem'], Object);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
NavItem.prototype.id = undefined;

/**
 * @member {String} link
 */
NavItem.prototype.link = undefined;

/**
 * @member {String} slug
 */
NavItem.prototype.slug = undefined;

/**
 * @member {String} label
 */
NavItem.prototype.label = undefined;

/**
 * @member {String} imageUrl
 */
NavItem.prototype.imageUrl = undefined;

/**
 * @member {Number} order
 */
NavItem.prototype.order = undefined;

/**
 * @member {Boolean} external
 */
NavItem.prototype.external = undefined;

/**
 * @member {Object} parentNavItem
 */
NavItem.prototype.parentNavItem = undefined;

/**
 * The date and time when this entry was created.
 * @member {Date} createdAt
 */
NavItem.prototype.createdAt = undefined;

/**
 * The date and time when this entry was last updated.
 * @member {Date} updatedAt
 */
NavItem.prototype.updatedAt = undefined;

