/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class Outcome.
 * @enum {String}
 * @readonly
 */
const Outcome = {
  /**
   * value: "loss"
   * @const
   */
  loss: "loss",

  /**
   * value: "win"
   * @const
   */
  win: "win",

  /**
   * Returns a <code>Outcome</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Outcome} The enum <code>Outcome</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Outcome};