/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class ParticipantId.
 * @enum {Number}
 * @readonly
 */
const ParticipantId = {
  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 3
   * @const
   */
  _3: 3,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 5
   * @const
   */
  _5: 5,

  /**
   * value: 6
   * @const
   */
  _6: 6,

  /**
   * value: 7
   * @const
   */
  _7: 7,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * value: 9
   * @const
   */
  _9: 9,

  /**
   * value: 10
   * @const
   */
  _10: 10,

  /**
   * Returns a <code>ParticipantId</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ParticipantId} The enum <code>ParticipantId</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ParticipantId};