/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ParticipantId} from './ParticipantId';
import {ParticipantMetadata} from './ParticipantMetadata';

/**
 * The ParticipantMetadataExtended model module.
 * @module model/ParticipantMetadataExtended
 * @version 1.0.0-alpha-1
 */
export class ParticipantMetadataExtended extends ParticipantMetadata {
  /**
   * Constructs a new <code>ParticipantMetadataExtended</code>.
   * @alias module:model/ParticipantMetadataExtended
   * @class
   * @extends module:model/ParticipantMetadata
   * @param participantId {} 
   * @param summonerName {} 
   * @param championId {} 
   * @param role {} 
   * @param esportsPlayerId {} 
   */
  constructor(participantId, summonerName, championId, role, esportsPlayerId) {
    super(participantId, summonerName, championId, role);
    this.esportsPlayerId = esportsPlayerId;
  }

  /**
   * Constructs a <code>ParticipantMetadataExtended</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ParticipantMetadataExtended} obj Optional instance to populate.
   * @return {module:model/ParticipantMetadataExtended} The populated <code>ParticipantMetadataExtended</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ParticipantMetadataExtended();
      ParticipantMetadata.constructFromObject(data, obj);
      if (data.hasOwnProperty('esportsPlayerId'))
        obj.esportsPlayerId = ApiClient.convertToType(data['esportsPlayerId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} esportsPlayerId
 */
ParticipantMetadataExtended.prototype.esportsPlayerId = undefined;

// Implement OneOfteamMetadataParticipantMetadataItems interface:
