/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Query model module.
 * @module model/Query
 * @version 1.0.0-alpha-1
 */
export class Query {
  /**
   * Constructs a new <code>Query</code>.
   * @alias module:model/Query
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Query</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Query} obj Optional instance to populate.
   * @return {module:model/Query} The populated <code>Query</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Query();
    }
    return obj;
  }
}
// Implement OneOfquery interface:
