/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Scores model module.
 * @module model/Scores
 * @version 1.0.0-alpha-1
 */
export class Scores {
  /**
   * Constructs a new <code>Scores</code>.
   * The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier) representing the roster ID. 
   * @alias module:model/Scores
   * @class
   * @extends Object
   */
  constructor() {
  }

  /**
   * Constructs a <code>Scores</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Scores} obj Optional instance to populate.
   * @return {module:model/Scores} The populated <code>Scores</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Scores();
      ApiClient.constructFromObject(data, obj, 'Number');
    }
    return obj;
  }
}
