/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ScoringOptions} from './ScoringOptions';

/**
 * The Scoring model module.
 * @module model/Scoring
 * @version 1.0.0-alpha-1
 */
export class Scoring {
  /**
   * Constructs a new <code>Scoring</code>.
   * @alias module:model/Scoring
   * @class
   * @param identifier {module:model/Scoring.IdentifierEnum} **Note:** The `LegacyScoringStrategy` value has only been found in the 2015 worlds championship.
   * @param options {module:model/ScoringOptions} 
   */
  constructor(identifier, options) {
    this.identifier = identifier;
    this.options = options;
  }

  /**
   * Constructs a <code>Scoring</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Scoring} obj Optional instance to populate.
   * @return {module:model/Scoring} The populated <code>Scoring</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Scoring();
      if (data.hasOwnProperty('identifier'))
        obj.identifier = ApiClient.convertToType(data['identifier'], 'String');
      if (data.hasOwnProperty('options'))
        obj.options = ScoringOptions.constructFromObject(data['options']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>identifier</code> property.
 * @enum {String}
 * @readonly
 */
Scoring.IdentifierEnum = {
  /**
   * value: "standard"
   * @const
   */
  standard: "standard",

  /**
   * value: "LegacyScoringStrategy"
   * @const
   */
  legacyScoringStrategy: "LegacyScoringStrategy"
};
/**
 * **Note:** The `LegacyScoringStrategy` value has only been found in the 2015 worlds championship.
 * @member {module:model/Scoring.IdentifierEnum} identifier
 */
Scoring.prototype.identifier = undefined;

/**
 * @member {module:model/ScoringOptions} options
 */
Scoring.prototype.options = undefined;

