/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SimpleEvent model module.
 * @module model/SimpleEvent
 * @version 1.0.0-alpha-1
 */
export class SimpleEvent {
  /**
   * Constructs a new <code>SimpleEvent</code>.
   * @alias module:model/SimpleEvent
   * @class
   * @param startTime {Date} The time the match started
   * @param blockName {String} 
   * @param match {Object} 
   */
  constructor(startTime, blockName, match) {
    this.startTime = startTime;
    this.blockName = blockName;
    this.match = match;
  }

  /**
   * Constructs a <code>SimpleEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimpleEvent} obj Optional instance to populate.
   * @return {module:model/SimpleEvent} The populated <code>SimpleEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SimpleEvent();
      if (data.hasOwnProperty('startTime'))
        obj.startTime = ApiClient.convertToType(data['startTime'], 'Date');
      if (data.hasOwnProperty('blockName'))
        obj.blockName = ApiClient.convertToType(data['blockName'], 'String');
      if (data.hasOwnProperty('match'))
        obj.match = ApiClient.convertToType(data['match'], Object);
    }
    return obj;
  }
}

/**
 * The time the match started
 * @member {Date} startTime
 */
SimpleEvent.prototype.startTime = undefined;

/**
 * @member {String} blockName
 */
SimpleEvent.prototype.blockName = undefined;

/**
 * @member {Object} match
 */
SimpleEvent.prototype.match = undefined;

