/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BaseMatch} from './BaseMatch';
import {Teams} from './Teams';

/**
 * The SimpleMatch model module.
 * @module model/SimpleMatch
 * @version 1.0.0-alpha-1
 */
export class SimpleMatch extends BaseMatch {
  /**
   * Constructs a new <code>SimpleMatch</code>.
   * @alias module:model/SimpleMatch
   * @class
   * @extends module:model/BaseMatch
   * @param teams {} 
   * @param id {} The match id
   */
  constructor(teams, id) {
    super(teams);
    this.id = id;
  }

  /**
   * Constructs a <code>SimpleMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimpleMatch} obj Optional instance to populate.
   * @return {module:model/SimpleMatch} The populated <code>SimpleMatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SimpleMatch();
      BaseMatch.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * The match id
 * @member {String} id
 */
SimpleMatch.prototype.id = undefined;

