/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TeamSlug model module.
 * @module model/TeamSlug
 * @version 1.0.0-alpha-1
 */
export class TeamSlug {
  /**
   * Constructs a new <code>TeamSlug</code>.
   * The URL friendly version of the team name
   * @alias module:model/TeamSlug
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TeamSlug</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamSlug} obj Optional instance to populate.
   * @return {module:model/TeamSlug} The populated <code>TeamSlug</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamSlug();
    }
    return obj;
  }
}
