/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Team} from './Team';

/**
 * The Teams model module.
 * @module model/Teams
 * @version 1.0.0-alpha-1
 */
export class Teams extends Array {
  /**
   * Constructs a new <code>Teams</code>.
   * @alias module:model/Teams
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Teams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Teams} obj Optional instance to populate.
   * @return {module:model/Teams} The populated <code>Teams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Teams();
      ApiClient.constructFromObject(data, obj, 'Team');
    }
    return obj;
  }
}
