/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GameMetadata} from './GameMetadata';
import {WindowFrame} from './WindowFrame';

/**
 * The Window model module.
 * @module model/Window
 * @version 1.0.0-alpha-1
 */
export class Window {
  /**
   * Constructs a new <code>Window</code>.
   * @alias module:model/Window
   * @class
   * @param esportsGameId {String} The game Id of the match
   * @param esportsMatchId {String} The match Id of the match
   * @param gameMetadata {module:model/GameMetadata} 
   * @param frames {Array.<module:model/WindowFrame>} 
   */
  constructor(esportsGameId, esportsMatchId, gameMetadata, frames) {
    this.esportsGameId = esportsGameId;
    this.esportsMatchId = esportsMatchId;
    this.gameMetadata = gameMetadata;
    this.frames = frames;
  }

  /**
   * Constructs a <code>Window</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Window} obj Optional instance to populate.
   * @return {module:model/Window} The populated <code>Window</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Window();
      if (data.hasOwnProperty('esportsGameId'))
        obj.esportsGameId = ApiClient.convertToType(data['esportsGameId'], 'String');
      if (data.hasOwnProperty('esportsMatchId'))
        obj.esportsMatchId = ApiClient.convertToType(data['esportsMatchId'], 'String');
      if (data.hasOwnProperty('gameMetadata'))
        obj.gameMetadata = GameMetadata.constructFromObject(data['gameMetadata']);
      if (data.hasOwnProperty('frames'))
        obj.frames = ApiClient.convertToType(data['frames'], [WindowFrame]);
    }
    return obj;
  }
}

/**
 * The game Id of the match
 * @member {String} esportsGameId
 */
Window.prototype.esportsGameId = undefined;

/**
 * The match Id of the match
 * @member {String} esportsMatchId
 */
Window.prototype.esportsMatchId = undefined;

/**
 * @member {module:model/GameMetadata} gameMetadata
 */
Window.prototype.gameMetadata = undefined;

/**
 * @member {Array.<module:model/WindowFrame>} frames
 */
Window.prototype.frames = undefined;

