/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AllOfinlineResponse2006DataEvent', function() {
      beforeEach(function() {
        instance = new LolesportsApi.AllOfinlineResponse2006DataEvent();
      });

      it('should create an instance of AllOfinlineResponse2006DataEvent', function() {
        // TODO: update the code to test AllOfinlineResponse2006DataEvent
        expect(instance).to.be.a(LolesportsApi.AllOfinlineResponse2006DataEvent);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property league (base name: "league")', function() {
        // TODO: update the code to test the property league
        expect(instance).to.have.property('league');
        // expect(instance.league).to.be(expectedValueLiteral);
      });

      it('should have the property match (base name: "match")', function() {
        // TODO: update the code to test the property match
        expect(instance).to.have.property('match');
        // expect(instance.match).to.be(expectedValueLiteral);
      });

      it('should have the property streams (base name: "streams")', function() {
        // TODO: update the code to test the property streams
        expect(instance).to.have.property('streams');
        // expect(instance.streams).to.be(expectedValueLiteral);
      });

    });
  });

}));
