/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GameMode', function() {
      beforeEach(function() {
        instance = new LolesportsApi.GameMode();
      });

      it('should create an instance of GameMode', function() {
        // TODO: update the code to test GameMode
        expect(instance).to.be.a(LolesportsApi.GameMode);
      });

      it('should have the property identifier (base name: "identifier")', function() {
        // TODO: update the code to test the property identifier
        expect(instance).to.have.property('identifier');
        // expect(instance.identifier).to.be(expectedValueLiteral);
      });

      it('should have the property requiredPlayers (base name: "requiredPlayers")', function() {
        // TODO: update the code to test the property requiredPlayers
        expect(instance).to.have.property('requiredPlayers');
        // expect(instance.requiredPlayers).to.be(expectedValueLiteral);
      });

      it('should have the property mapName (base name: "mapName")', function() {
        // TODO: update the code to test the property mapName
        expect(instance).to.have.property('mapName');
        // expect(instance.mapName).to.be(expectedValueLiteral);
      });

    });
  });

}));
