/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('HighlanderPlayer', function() {
      beforeEach(function() {
        instance = new LolesportsApi.HighlanderPlayer();
      });

      it('should create an instance of HighlanderPlayer', function() {
        // TODO: update the code to test HighlanderPlayer
        expect(instance).to.be.a(LolesportsApi.HighlanderPlayer);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property slug (base name: "slug")', function() {
        // TODO: update the code to test the property slug
        expect(instance).to.have.property('slug');
        // expect(instance.slug).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property firstName (base name: "firstName")', function() {
        // TODO: update the code to test the property firstName
        expect(instance).to.have.property('firstName');
        // expect(instance.firstName).to.be(expectedValueLiteral);
      });

      it('should have the property lastName (base name: "LastName")', function() {
        // TODO: update the code to test the property lastName
        expect(instance).to.have.property('lastName');
        // expect(instance.lastName).to.be(expectedValueLiteral);
      });

      it('should have the property roleSlug (base name: "roleSlug")', function() {
        // TODO: update the code to test the property roleSlug
        expect(instance).to.have.property('roleSlug');
        // expect(instance.roleSlug).to.be(expectedValueLiteral);
      });

      it('should have the property photoUrl (base name: "photoUrl")', function() {
        // TODO: update the code to test the property photoUrl
        expect(instance).to.have.property('photoUrl');
        // expect(instance.photoUrl).to.be(expectedValueLiteral);
      });

      it('should have the property hometown (base name: "hometown")', function() {
        // TODO: update the code to test the property hometown
        expect(instance).to.have.property('hometown');
        // expect(instance.hometown).to.be(expectedValueLiteral);
      });

      it('should have the property region (base name: "region")', function() {
        // TODO: update the code to test the property region
        expect(instance).to.have.property('region');
        // expect(instance.region).to.be(expectedValueLiteral);
      });

      it('should have the property birthdate (base name: "birthdate")', function() {
        // TODO: update the code to test the property birthdate
        expect(instance).to.have.property('birthdate');
        // expect(instance.birthdate).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property bios (base name: "bios")', function() {
        // TODO: update the code to test the property bios
        expect(instance).to.have.property('bios');
        // expect(instance.bios).to.be(expectedValueLiteral);
      });

      it('should have the property foreignIds (base name: "foreignIds")', function() {
        // TODO: update the code to test the property foreignIds
        expect(instance).to.have.property('foreignIds');
        // expect(instance.foreignIds).to.be(expectedValueLiteral);
      });

      it('should have the property socialNetworks (base name: "socialNetworks")', function() {
        // TODO: update the code to test the property socialNetworks
        expect(instance).to.have.property('socialNetworks');
        // expect(instance.socialNetworks).to.be(expectedValueLiteral);
      });

      it('should have the property champions (base name: "champions")', function() {
        // TODO: update the code to test the property champions
        expect(instance).to.have.property('champions');
        // expect(instance.champions).to.be(expectedValueLiteral);
      });

    });
  });

}));
