/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2001DataSchedulePages', function() {
      beforeEach(function() {
        instance = new LolesportsApi.InlineResponse2001DataSchedulePages();
      });

      it('should create an instance of InlineResponse2001DataSchedulePages', function() {
        // TODO: update the code to test InlineResponse2001DataSchedulePages
        expect(instance).to.be.a(LolesportsApi.InlineResponse2001DataSchedulePages);
      });

      it('should have the property older (base name: "older")', function() {
        // TODO: update the code to test the property older
        expect(instance).to.have.property('older');
        // expect(instance.older).to.be(expectedValueLiteral);
      });

      it('should have the property newer (base name: "newer")', function() {
        // TODO: update the code to test the property newer
        expect(instance).to.have.property('newer');
        // expect(instance.newer).to.be(expectedValueLiteral);
      });

    });
  });

}));
