/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ParticipantStats', function() {
      beforeEach(function() {
        instance = new LolesportsApi.ParticipantStats();
      });

      it('should create an instance of ParticipantStats', function() {
        // TODO: update the code to test ParticipantStats
        expect(instance).to.be.a(LolesportsApi.ParticipantStats);
      });

      it('should have the property totalGold (base name: "totalGold")', function() {
        // TODO: update the code to test the property totalGold
        expect(instance).to.have.property('totalGold');
        // expect(instance.totalGold).to.be(expectedValueLiteral);
      });

      it('should have the property currentHealth (base name: "currentHealth")', function() {
        // TODO: update the code to test the property currentHealth
        expect(instance).to.have.property('currentHealth');
        // expect(instance.currentHealth).to.be(expectedValueLiteral);
      });

      it('should have the property maxHealth (base name: "maxHealth")', function() {
        // TODO: update the code to test the property maxHealth
        expect(instance).to.have.property('maxHealth');
        // expect(instance.maxHealth).to.be(expectedValueLiteral);
      });

    });
  });

}));
