/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ParticipantMetadata', function() {
      beforeEach(function() {
        instance = new LolesportsApi.ParticipantMetadata();
      });

      it('should create an instance of ParticipantMetadata', function() {
        // TODO: update the code to test ParticipantMetadata
        expect(instance).to.be.a(LolesportsApi.ParticipantMetadata);
      });

      it('should have the property participantId (base name: "participantId")', function() {
        // TODO: update the code to test the property participantId
        expect(instance).to.have.property('participantId');
        // expect(instance.participantId).to.be(expectedValueLiteral);
      });

      it('should have the property summonerName (base name: "summonerName")', function() {
        // TODO: update the code to test the property summonerName
        expect(instance).to.have.property('summonerName');
        // expect(instance.summonerName).to.be(expectedValueLiteral);
      });

      it('should have the property championId (base name: "championId")', function() {
        // TODO: update the code to test the property championId
        expect(instance).to.have.property('championId');
        // expect(instance.championId).to.be(expectedValueLiteral);
      });

      it('should have the property role (base name: "role")', function() {
        // TODO: update the code to test the property role
        expect(instance).to.have.property('role');
        // expect(instance.role).to.be(expectedValueLiteral);
      });

    });
  });

}));
