/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PerkMetadata', function() {
      beforeEach(function() {
        instance = new LolesportsApi.PerkMetadata();
      });

      it('should create an instance of PerkMetadata', function() {
        // TODO: update the code to test PerkMetadata
        expect(instance).to.be.a(LolesportsApi.PerkMetadata);
      });

      it('should have the property styleId (base name: "styleId")', function() {
        // TODO: update the code to test the property styleId
        expect(instance).to.have.property('styleId');
        // expect(instance.styleId).to.be(expectedValueLiteral);
      });

      it('should have the property subStyleId (base name: "subStyleId")', function() {
        // TODO: update the code to test the property subStyleId
        expect(instance).to.have.property('subStyleId');
        // expect(instance.subStyleId).to.be(expectedValueLiteral);
      });

      it('should have the property perks (base name: "perks")', function() {
        // TODO: update the code to test the property perks
        expect(instance).to.have.property('perks');
        // expect(instance.perks).to.be(expectedValueLiteral);
      });

    });
  });

}));
