/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LolesportsApi);
  }
}(this, function(expect, LolesportsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Section', function() {
      beforeEach(function() {
        instance = new LolesportsApi.Section();
      });

      it('should create an instance of Section', function() {
        // TODO: update the code to test Section
        expect(instance).to.be.a(LolesportsApi.Section);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property matches (base name: "matches")', function() {
        // TODO: update the code to test the property matches
        expect(instance).to.have.property('matches');
        // expect(instance.matches).to.be(expectedValueLiteral);
      });

      it('should have the property rankings (base name: "rankings")', function() {
        // TODO: update the code to test the property rankings
        expect(instance).to.have.property('rankings');
        // expect(instance.rankings).to.be(expectedValueLiteral);
      });

    });
  });

}));
