/*
 * Lolesports Api
 * Unofficial documentation to the lolesports Api
 *
 * OpenAPI spec version: 1.0.0-alpha-1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Abilities} from './model/Abilities';
import {AllOfhighlanderGameInputItems} from './model/AllOfhighlanderGameInputItems';
import {AllOfhighlanderMatchInputItems} from './model/AllOfhighlanderMatchInputItems';
import {AllOfhighlanderPlayerForeignIds} from './model/AllOfhighlanderPlayerForeignIds';
import {AllOfinlineResponse20014PlayersItems} from './model/AllOfinlineResponse20014PlayersItems';
import {AllOfinlineResponse20015PlayersItems} from './model/AllOfinlineResponse20015PlayersItems';
import {AllOfinlineResponse2001DataScheduleEventsItems} from './model/AllOfinlineResponse2001DataScheduleEventsItems';
import {AllOfinlineResponse2002DataScheduleEventsItems} from './model/AllOfinlineResponse2002DataScheduleEventsItems';
import {AllOfinlineResponse2005DataScheduleEventsItems} from './model/AllOfinlineResponse2005DataScheduleEventsItems';
import {AllOfinlineResponse2006DataEvent} from './model/AllOfinlineResponse2006DataEvent';
import {AllOfinlineResponse200DataLeaguesItems} from './model/AllOfinlineResponse200DataLeaguesItems';
import {AllOfnavItemParentNavItem} from './model/AllOfnavItemParentNavItem';
import {AllOfrankingTeamsItems} from './model/AllOfrankingTeamsItems';
import {AllOfsectionMatchesItems} from './model/AllOfsectionMatchesItems';
import {AllOfsimpleEventMatch} from './model/AllOfsimpleEventMatch';
import {BaseEvent} from './model/BaseEvent';
import {BaseFrame} from './model/BaseFrame';
import {BaseLeague} from './model/BaseLeague';
import {BaseMatch} from './model/BaseMatch';
import {BaseParticipantStats} from './model/BaseParticipantStats';
import {BaseScheduleItem} from './model/BaseScheduleItem';
import {BaseStrategy} from './model/BaseStrategy';
import {BracketType} from './model/BracketType';
import {BracketTypeOptions} from './model/BracketTypeOptions';
import {Brackets} from './model/Brackets';
import {Breakpoints} from './model/Breakpoints';
import {CustomTeam} from './model/CustomTeam';
import {DetailsFrame} from './model/DetailsFrame';
import {EventScheduleItem} from './model/EventScheduleItem';
import {EventType} from './model/EventType';
import {ExtendedEvent} from './model/ExtendedEvent';
import {ExtendedGame} from './model/ExtendedGame';
import {ExtendedLeague} from './model/ExtendedLeague';
import {ExtendedParticipantStats} from './model/ExtendedParticipantStats';
import {ExtendedTeam} from './model/ExtendedTeam';
import {ExtendedVod} from './model/ExtendedVod';
import {ForeignIds} from './model/ForeignIds';
import {Game} from './model/Game';
import {GameId} from './model/GameId';
import {GameMetadata} from './model/GameMetadata';
import {GameMode} from './model/GameMode';
import {HighlanderGame} from './model/HighlanderGame';
import {HighlanderLeague} from './model/HighlanderLeague';
import {HighlanderMatch} from './model/HighlanderMatch';
import {HighlanderPlayer} from './model/HighlanderPlayer';
import {HighlanderPlayerChampions} from './model/HighlanderPlayerChampions';
import {HighlanderPlayers} from './model/HighlanderPlayers';
import {HighlanderRecord} from './model/HighlanderRecord';
import {HighlanderRecords} from './model/HighlanderRecords';
import {HighlanderResult} from './model/HighlanderResult';
import {HighlanderTeam} from './model/HighlanderTeam';
import {HighlanderTeams} from './model/HighlanderTeams';
import {HighlanderTournament} from './model/HighlanderTournament';
import {HighlanderTournamentRosters} from './model/HighlanderTournamentRosters';
import {HighlanderTournaments} from './model/HighlanderTournaments';
import {HomeLeague} from './model/HomeLeague';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse20010} from './model/InlineResponse20010';
import {InlineResponse20011} from './model/InlineResponse20011';
import {InlineResponse20012} from './model/InlineResponse20012';
import {InlineResponse20013} from './model/InlineResponse20013';
import {InlineResponse20014} from './model/InlineResponse20014';
import {InlineResponse20014AverageDamageByPosition} from './model/InlineResponse20014AverageDamageByPosition';
import {InlineResponse20014TeamRosterStats} from './model/InlineResponse20014TeamRosterStats';
import {InlineResponse20014TeamStatsHistories} from './model/InlineResponse20014TeamStatsHistories';
import {InlineResponse20014TeamStatsSummaries} from './model/InlineResponse20014TeamStatsSummaries';
import {InlineResponse20015} from './model/InlineResponse20015';
import {InlineResponse20015Mostplayedchampions} from './model/InlineResponse20015Mostplayedchampions';
import {InlineResponse20015PlayerStatsHistories} from './model/InlineResponse20015PlayerStatsHistories';
import {InlineResponse20015PlayerStatsSummaries} from './model/InlineResponse20015PlayerStatsSummaries';
import {InlineResponse2001Data} from './model/InlineResponse2001Data';
import {InlineResponse2001DataSchedule} from './model/InlineResponse2001DataSchedule';
import {InlineResponse2001DataSchedulePages} from './model/InlineResponse2001DataSchedulePages';
import {InlineResponse2002} from './model/InlineResponse2002';
import {InlineResponse2002Data} from './model/InlineResponse2002Data';
import {InlineResponse2002DataSchedule} from './model/InlineResponse2002DataSchedule';
import {InlineResponse2003} from './model/InlineResponse2003';
import {InlineResponse2003Data} from './model/InlineResponse2003Data';
import {InlineResponse2003DataLeagues} from './model/InlineResponse2003DataLeagues';
import {InlineResponse2004} from './model/InlineResponse2004';
import {InlineResponse2004Data} from './model/InlineResponse2004Data';
import {InlineResponse2004DataStandings} from './model/InlineResponse2004DataStandings';
import {InlineResponse2005} from './model/InlineResponse2005';
import {InlineResponse2005Data} from './model/InlineResponse2005Data';
import {InlineResponse2005DataSchedule} from './model/InlineResponse2005DataSchedule';
import {InlineResponse2006} from './model/InlineResponse2006';
import {InlineResponse2006Data} from './model/InlineResponse2006Data';
import {InlineResponse2007} from './model/InlineResponse2007';
import {InlineResponse2007Data} from './model/InlineResponse2007Data';
import {InlineResponse2008} from './model/InlineResponse2008';
import {InlineResponse2008Data} from './model/InlineResponse2008Data';
import {InlineResponse2009} from './model/InlineResponse2009';
import {InlineResponse200Data} from './model/InlineResponse200Data';
import {InlineResponse404} from './model/InlineResponse404';
import {InlineResponse4041} from './model/InlineResponse4041';
import {InlineResponse404Error} from './model/InlineResponse404Error';
import {Locale} from './model/Locale';
import {MatchScheduleItem} from './model/MatchScheduleItem';
import {MatchType} from './model/MatchType';
import {MatchTypeOptions} from './model/MatchTypeOptions';
import {NavItem} from './model/NavItem';
import {OneOfquery} from './model/OneOfquery';
import {OneOfscheduleItem} from './model/OneOfscheduleItem';
import {OneOfteamMetadataParticipantMetadataItems} from './model/OneOfteamMetadataParticipantMetadataItems';
import {Outcome} from './model/Outcome';
import {PageToken} from './model/PageToken';
import {ParticipantId} from './model/ParticipantId';
import {ParticipantMetadata} from './model/ParticipantMetadata';
import {ParticipantMetadataExtended} from './model/ParticipantMetadataExtended';
import {ParticipantStats} from './model/ParticipantStats';
import {PerkMetadata} from './model/PerkMetadata';
import {Player} from './model/Player';
import {Query} from './model/Query';
import {Ranking} from './model/Ranking';
import {Record} from './model/Record';
import {Result} from './model/Result';
import {Role} from './model/Role';
import {Roles} from './model/Roles';
import {RosteringStrategy} from './model/RosteringStrategy';
import {ScheduleItem} from './model/ScheduleItem';
import {Scores} from './model/Scores';
import {Scoring} from './model/Scoring';
import {ScoringOptions} from './model/ScoringOptions';
import {Section} from './model/Section';
import {SimpleEvent} from './model/SimpleEvent';
import {SimpleGame} from './model/SimpleGame';
import {SimpleLeague} from './model/SimpleLeague';
import {SimpleMatch} from './model/SimpleMatch';
import {SimpleRoster} from './model/SimpleRoster';
import {Stage} from './model/Stage';
import {Standings} from './model/Standings';
import {State} from './model/State';
import {Strategy} from './model/Strategy';
import {Tags} from './model/Tags';
import {Team} from './model/Team';
import {TeamId} from './model/TeamId';
import {TeamMetadata} from './model/TeamMetadata';
import {TeamSlug} from './model/TeamSlug';
import {TeamStats} from './model/TeamStats';
import {Teams} from './model/Teams';
import {Tournament} from './model/Tournament';
import {Video} from './model/Video';
import {Vod} from './model/Vod';
import {Window} from './model/Window';
import {WindowFrame} from './model/WindowFrame';
import {EventsApi} from './api/EventsApi';
import {HighlanderApi} from './api/HighlanderApi';
import {LeaguesApi} from './api/LeaguesApi';
import {MatchDetailsApi} from './api/MatchDetailsApi';
import {TeamsApi} from './api/TeamsApi';

/**
* Unofficial_documentation_to_the_lolesports_Api.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LolesportsApi = require('index'); // See note below*.
* var xxxSvc = new LolesportsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LolesportsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LolesportsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LolesportsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0-alpha-1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Abilities model constructor.
     * @property {module:model/Abilities}
     */
    Abilities,

    /**
     * The AllOfhighlanderGameInputItems model constructor.
     * @property {module:model/AllOfhighlanderGameInputItems}
     */
    AllOfhighlanderGameInputItems,

    /**
     * The AllOfhighlanderMatchInputItems model constructor.
     * @property {module:model/AllOfhighlanderMatchInputItems}
     */
    AllOfhighlanderMatchInputItems,

    /**
     * The AllOfhighlanderPlayerForeignIds model constructor.
     * @property {module:model/AllOfhighlanderPlayerForeignIds}
     */
    AllOfhighlanderPlayerForeignIds,

    /**
     * The AllOfinlineResponse20014PlayersItems model constructor.
     * @property {module:model/AllOfinlineResponse20014PlayersItems}
     */
    AllOfinlineResponse20014PlayersItems,

    /**
     * The AllOfinlineResponse20015PlayersItems model constructor.
     * @property {module:model/AllOfinlineResponse20015PlayersItems}
     */
    AllOfinlineResponse20015PlayersItems,

    /**
     * The AllOfinlineResponse2001DataScheduleEventsItems model constructor.
     * @property {module:model/AllOfinlineResponse2001DataScheduleEventsItems}
     */
    AllOfinlineResponse2001DataScheduleEventsItems,

    /**
     * The AllOfinlineResponse2002DataScheduleEventsItems model constructor.
     * @property {module:model/AllOfinlineResponse2002DataScheduleEventsItems}
     */
    AllOfinlineResponse2002DataScheduleEventsItems,

    /**
     * The AllOfinlineResponse2005DataScheduleEventsItems model constructor.
     * @property {module:model/AllOfinlineResponse2005DataScheduleEventsItems}
     */
    AllOfinlineResponse2005DataScheduleEventsItems,

    /**
     * The AllOfinlineResponse2006DataEvent model constructor.
     * @property {module:model/AllOfinlineResponse2006DataEvent}
     */
    AllOfinlineResponse2006DataEvent,

    /**
     * The AllOfinlineResponse200DataLeaguesItems model constructor.
     * @property {module:model/AllOfinlineResponse200DataLeaguesItems}
     */
    AllOfinlineResponse200DataLeaguesItems,

    /**
     * The AllOfnavItemParentNavItem model constructor.
     * @property {module:model/AllOfnavItemParentNavItem}
     */
    AllOfnavItemParentNavItem,

    /**
     * The AllOfrankingTeamsItems model constructor.
     * @property {module:model/AllOfrankingTeamsItems}
     */
    AllOfrankingTeamsItems,

    /**
     * The AllOfsectionMatchesItems model constructor.
     * @property {module:model/AllOfsectionMatchesItems}
     */
    AllOfsectionMatchesItems,

    /**
     * The AllOfsimpleEventMatch model constructor.
     * @property {module:model/AllOfsimpleEventMatch}
     */
    AllOfsimpleEventMatch,

    /**
     * The BaseEvent model constructor.
     * @property {module:model/BaseEvent}
     */
    BaseEvent,

    /**
     * The BaseFrame model constructor.
     * @property {module:model/BaseFrame}
     */
    BaseFrame,

    /**
     * The BaseLeague model constructor.
     * @property {module:model/BaseLeague}
     */
    BaseLeague,

    /**
     * The BaseMatch model constructor.
     * @property {module:model/BaseMatch}
     */
    BaseMatch,

    /**
     * The BaseParticipantStats model constructor.
     * @property {module:model/BaseParticipantStats}
     */
    BaseParticipantStats,

    /**
     * The BaseScheduleItem model constructor.
     * @property {module:model/BaseScheduleItem}
     */
    BaseScheduleItem,

    /**
     * The BaseStrategy model constructor.
     * @property {module:model/BaseStrategy}
     */
    BaseStrategy,

    /**
     * The BracketType model constructor.
     * @property {module:model/BracketType}
     */
    BracketType,

    /**
     * The BracketTypeOptions model constructor.
     * @property {module:model/BracketTypeOptions}
     */
    BracketTypeOptions,

    /**
     * The Brackets model constructor.
     * @property {module:model/Brackets}
     */
    Brackets,

    /**
     * The Breakpoints model constructor.
     * @property {module:model/Breakpoints}
     */
    Breakpoints,

    /**
     * The CustomTeam model constructor.
     * @property {module:model/CustomTeam}
     */
    CustomTeam,

    /**
     * The DetailsFrame model constructor.
     * @property {module:model/DetailsFrame}
     */
    DetailsFrame,

    /**
     * The EventScheduleItem model constructor.
     * @property {module:model/EventScheduleItem}
     */
    EventScheduleItem,

    /**
     * The EventType model constructor.
     * @property {module:model/EventType}
     */
    EventType,

    /**
     * The ExtendedEvent model constructor.
     * @property {module:model/ExtendedEvent}
     */
    ExtendedEvent,

    /**
     * The ExtendedGame model constructor.
     * @property {module:model/ExtendedGame}
     */
    ExtendedGame,

    /**
     * The ExtendedLeague model constructor.
     * @property {module:model/ExtendedLeague}
     */
    ExtendedLeague,

    /**
     * The ExtendedParticipantStats model constructor.
     * @property {module:model/ExtendedParticipantStats}
     */
    ExtendedParticipantStats,

    /**
     * The ExtendedTeam model constructor.
     * @property {module:model/ExtendedTeam}
     */
    ExtendedTeam,

    /**
     * The ExtendedVod model constructor.
     * @property {module:model/ExtendedVod}
     */
    ExtendedVod,

    /**
     * The ForeignIds model constructor.
     * @property {module:model/ForeignIds}
     */
    ForeignIds,

    /**
     * The Game model constructor.
     * @property {module:model/Game}
     */
    Game,

    /**
     * The GameId model constructor.
     * @property {module:model/GameId}
     */
    GameId,

    /**
     * The GameMetadata model constructor.
     * @property {module:model/GameMetadata}
     */
    GameMetadata,

    /**
     * The GameMode model constructor.
     * @property {module:model/GameMode}
     */
    GameMode,

    /**
     * The HighlanderGame model constructor.
     * @property {module:model/HighlanderGame}
     */
    HighlanderGame,

    /**
     * The HighlanderLeague model constructor.
     * @property {module:model/HighlanderLeague}
     */
    HighlanderLeague,

    /**
     * The HighlanderMatch model constructor.
     * @property {module:model/HighlanderMatch}
     */
    HighlanderMatch,

    /**
     * The HighlanderPlayer model constructor.
     * @property {module:model/HighlanderPlayer}
     */
    HighlanderPlayer,

    /**
     * The HighlanderPlayerChampions model constructor.
     * @property {module:model/HighlanderPlayerChampions}
     */
    HighlanderPlayerChampions,

    /**
     * The HighlanderPlayers model constructor.
     * @property {module:model/HighlanderPlayers}
     */
    HighlanderPlayers,

    /**
     * The HighlanderRecord model constructor.
     * @property {module:model/HighlanderRecord}
     */
    HighlanderRecord,

    /**
     * The HighlanderRecords model constructor.
     * @property {module:model/HighlanderRecords}
     */
    HighlanderRecords,

    /**
     * The HighlanderResult model constructor.
     * @property {module:model/HighlanderResult}
     */
    HighlanderResult,

    /**
     * The HighlanderTeam model constructor.
     * @property {module:model/HighlanderTeam}
     */
    HighlanderTeam,

    /**
     * The HighlanderTeams model constructor.
     * @property {module:model/HighlanderTeams}
     */
    HighlanderTeams,

    /**
     * The HighlanderTournament model constructor.
     * @property {module:model/HighlanderTournament}
     */
    HighlanderTournament,

    /**
     * The HighlanderTournamentRosters model constructor.
     * @property {module:model/HighlanderTournamentRosters}
     */
    HighlanderTournamentRosters,

    /**
     * The HighlanderTournaments model constructor.
     * @property {module:model/HighlanderTournaments}
     */
    HighlanderTournaments,

    /**
     * The HomeLeague model constructor.
     * @property {module:model/HomeLeague}
     */
    HomeLeague,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20014AverageDamageByPosition model constructor.
     * @property {module:model/InlineResponse20014AverageDamageByPosition}
     */
    InlineResponse20014AverageDamageByPosition,

    /**
     * The InlineResponse20014TeamRosterStats model constructor.
     * @property {module:model/InlineResponse20014TeamRosterStats}
     */
    InlineResponse20014TeamRosterStats,

    /**
     * The InlineResponse20014TeamStatsHistories model constructor.
     * @property {module:model/InlineResponse20014TeamStatsHistories}
     */
    InlineResponse20014TeamStatsHistories,

    /**
     * The InlineResponse20014TeamStatsSummaries model constructor.
     * @property {module:model/InlineResponse20014TeamStatsSummaries}
     */
    InlineResponse20014TeamStatsSummaries,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse20015Mostplayedchampions model constructor.
     * @property {module:model/InlineResponse20015Mostplayedchampions}
     */
    InlineResponse20015Mostplayedchampions,

    /**
     * The InlineResponse20015PlayerStatsHistories model constructor.
     * @property {module:model/InlineResponse20015PlayerStatsHistories}
     */
    InlineResponse20015PlayerStatsHistories,

    /**
     * The InlineResponse20015PlayerStatsSummaries model constructor.
     * @property {module:model/InlineResponse20015PlayerStatsSummaries}
     */
    InlineResponse20015PlayerStatsSummaries,

    /**
     * The InlineResponse2001Data model constructor.
     * @property {module:model/InlineResponse2001Data}
     */
    InlineResponse2001Data,

    /**
     * The InlineResponse2001DataSchedule model constructor.
     * @property {module:model/InlineResponse2001DataSchedule}
     */
    InlineResponse2001DataSchedule,

    /**
     * The InlineResponse2001DataSchedulePages model constructor.
     * @property {module:model/InlineResponse2001DataSchedulePages}
     */
    InlineResponse2001DataSchedulePages,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2002Data model constructor.
     * @property {module:model/InlineResponse2002Data}
     */
    InlineResponse2002Data,

    /**
     * The InlineResponse2002DataSchedule model constructor.
     * @property {module:model/InlineResponse2002DataSchedule}
     */
    InlineResponse2002DataSchedule,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2003Data model constructor.
     * @property {module:model/InlineResponse2003Data}
     */
    InlineResponse2003Data,

    /**
     * The InlineResponse2003DataLeagues model constructor.
     * @property {module:model/InlineResponse2003DataLeagues}
     */
    InlineResponse2003DataLeagues,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2004Data model constructor.
     * @property {module:model/InlineResponse2004Data}
     */
    InlineResponse2004Data,

    /**
     * The InlineResponse2004DataStandings model constructor.
     * @property {module:model/InlineResponse2004DataStandings}
     */
    InlineResponse2004DataStandings,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2005Data model constructor.
     * @property {module:model/InlineResponse2005Data}
     */
    InlineResponse2005Data,

    /**
     * The InlineResponse2005DataSchedule model constructor.
     * @property {module:model/InlineResponse2005DataSchedule}
     */
    InlineResponse2005DataSchedule,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2006Data model constructor.
     * @property {module:model/InlineResponse2006Data}
     */
    InlineResponse2006Data,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2007Data model constructor.
     * @property {module:model/InlineResponse2007Data}
     */
    InlineResponse2007Data,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2008Data model constructor.
     * @property {module:model/InlineResponse2008Data}
     */
    InlineResponse2008Data,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse200Data model constructor.
     * @property {module:model/InlineResponse200Data}
     */
    InlineResponse200Data,

    /**
     * The InlineResponse404 model constructor.
     * @property {module:model/InlineResponse404}
     */
    InlineResponse404,

    /**
     * The InlineResponse4041 model constructor.
     * @property {module:model/InlineResponse4041}
     */
    InlineResponse4041,

    /**
     * The InlineResponse404Error model constructor.
     * @property {module:model/InlineResponse404Error}
     */
    InlineResponse404Error,

    /**
     * The Locale model constructor.
     * @property {module:model/Locale}
     */
    Locale,

    /**
     * The MatchScheduleItem model constructor.
     * @property {module:model/MatchScheduleItem}
     */
    MatchScheduleItem,

    /**
     * The MatchType model constructor.
     * @property {module:model/MatchType}
     */
    MatchType,

    /**
     * The MatchTypeOptions model constructor.
     * @property {module:model/MatchTypeOptions}
     */
    MatchTypeOptions,

    /**
     * The NavItem model constructor.
     * @property {module:model/NavItem}
     */
    NavItem,

    /**
     * The OneOfquery model constructor.
     * @property {module:model/OneOfquery}
     */
    OneOfquery,

    /**
     * The OneOfscheduleItem model constructor.
     * @property {module:model/OneOfscheduleItem}
     */
    OneOfscheduleItem,

    /**
     * The OneOfteamMetadataParticipantMetadataItems model constructor.
     * @property {module:model/OneOfteamMetadataParticipantMetadataItems}
     */
    OneOfteamMetadataParticipantMetadataItems,

    /**
     * The Outcome model constructor.
     * @property {module:model/Outcome}
     */
    Outcome,

    /**
     * The PageToken model constructor.
     * @property {module:model/PageToken}
     */
    PageToken,

    /**
     * The ParticipantId model constructor.
     * @property {module:model/ParticipantId}
     */
    ParticipantId,

    /**
     * The ParticipantMetadata model constructor.
     * @property {module:model/ParticipantMetadata}
     */
    ParticipantMetadata,

    /**
     * The ParticipantMetadataExtended model constructor.
     * @property {module:model/ParticipantMetadataExtended}
     */
    ParticipantMetadataExtended,

    /**
     * The ParticipantStats model constructor.
     * @property {module:model/ParticipantStats}
     */
    ParticipantStats,

    /**
     * The PerkMetadata model constructor.
     * @property {module:model/PerkMetadata}
     */
    PerkMetadata,

    /**
     * The Player model constructor.
     * @property {module:model/Player}
     */
    Player,

    /**
     * The Query model constructor.
     * @property {module:model/Query}
     */
    Query,

    /**
     * The Ranking model constructor.
     * @property {module:model/Ranking}
     */
    Ranking,

    /**
     * The Record model constructor.
     * @property {module:model/Record}
     */
    Record,

    /**
     * The Result model constructor.
     * @property {module:model/Result}
     */
    Result,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The Roles model constructor.
     * @property {module:model/Roles}
     */
    Roles,

    /**
     * The RosteringStrategy model constructor.
     * @property {module:model/RosteringStrategy}
     */
    RosteringStrategy,

    /**
     * The ScheduleItem model constructor.
     * @property {module:model/ScheduleItem}
     */
    ScheduleItem,

    /**
     * The Scores model constructor.
     * @property {module:model/Scores}
     */
    Scores,

    /**
     * The Scoring model constructor.
     * @property {module:model/Scoring}
     */
    Scoring,

    /**
     * The ScoringOptions model constructor.
     * @property {module:model/ScoringOptions}
     */
    ScoringOptions,

    /**
     * The Section model constructor.
     * @property {module:model/Section}
     */
    Section,

    /**
     * The SimpleEvent model constructor.
     * @property {module:model/SimpleEvent}
     */
    SimpleEvent,

    /**
     * The SimpleGame model constructor.
     * @property {module:model/SimpleGame}
     */
    SimpleGame,

    /**
     * The SimpleLeague model constructor.
     * @property {module:model/SimpleLeague}
     */
    SimpleLeague,

    /**
     * The SimpleMatch model constructor.
     * @property {module:model/SimpleMatch}
     */
    SimpleMatch,

    /**
     * The SimpleRoster model constructor.
     * @property {module:model/SimpleRoster}
     */
    SimpleRoster,

    /**
     * The Stage model constructor.
     * @property {module:model/Stage}
     */
    Stage,

    /**
     * The Standings model constructor.
     * @property {module:model/Standings}
     */
    Standings,

    /**
     * The State model constructor.
     * @property {module:model/State}
     */
    State,

    /**
     * The Strategy model constructor.
     * @property {module:model/Strategy}
     */
    Strategy,

    /**
     * The Tags model constructor.
     * @property {module:model/Tags}
     */
    Tags,

    /**
     * The Team model constructor.
     * @property {module:model/Team}
     */
    Team,

    /**
     * The TeamId model constructor.
     * @property {module:model/TeamId}
     */
    TeamId,

    /**
     * The TeamMetadata model constructor.
     * @property {module:model/TeamMetadata}
     */
    TeamMetadata,

    /**
     * The TeamSlug model constructor.
     * @property {module:model/TeamSlug}
     */
    TeamSlug,

    /**
     * The TeamStats model constructor.
     * @property {module:model/TeamStats}
     */
    TeamStats,

    /**
     * The Teams model constructor.
     * @property {module:model/Teams}
     */
    Teams,

    /**
     * The Tournament model constructor.
     * @property {module:model/Tournament}
     */
    Tournament,

    /**
     * The Video model constructor.
     * @property {module:model/Video}
     */
    Video,

    /**
     * The Vod model constructor.
     * @property {module:model/Vod}
     */
    Vod,

    /**
     * The Window model constructor.
     * @property {module:model/Window}
     */
    Window,

    /**
     * The WindowFrame model constructor.
     * @property {module:model/WindowFrame}
     */
    WindowFrame,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The HighlanderApi service constructor.
    * @property {module:api/HighlanderApi}
    */
    HighlanderApi,

    /**
    * The LeaguesApi service constructor.
    * @property {module:api/LeaguesApi}
    */
    LeaguesApi,

    /**
    * The MatchDetailsApi service constructor.
    * @property {module:api/MatchDetailsApi}
    */
    MatchDetailsApi,

    /**
    * The TeamsApi service constructor.
    * @property {module:api/TeamsApi}
    */
    TeamsApi
};
